/*
Arcane API

Testing UpdaterAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package arcane

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/anujc4/arcane-go"
)

func Test_arcane_UpdaterAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test UpdaterAPIService GetUpdaterHistory", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.UpdaterAPI.GetUpdaterHistory(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test UpdaterAPIService GetUpdaterStatus", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.UpdaterAPI.GetUpdaterStatus(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test UpdaterAPIService RunUpdater", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.UpdaterAPI.RunUpdater(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test UpdaterAPIService UpdateContainer", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string
		var containerId string

		resp, httpRes, err := apiClient.UpdaterAPI.UpdateContainer(context.Background(), id, containerId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
