/*
Arcane API

Testing ContainersAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package arcane

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/anujc4/arcane-go"
)

func Test_arcane_ContainersAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ContainersAPIService ContainerStatusCounts", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.ContainersAPI.ContainerStatusCounts(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ContainersAPIService CreateContainer", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.ContainersAPI.CreateContainer(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ContainersAPIService DeleteContainer", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string
		var containerId string

		resp, httpRes, err := apiClient.ContainersAPI.DeleteContainer(context.Background(), id, containerId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ContainersAPIService GetContainer", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string
		var containerId string

		resp, httpRes, err := apiClient.ContainersAPI.GetContainer(context.Background(), id, containerId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ContainersAPIService ListContainers", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.ContainersAPI.ListContainers(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ContainersAPIService RestartContainer", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string
		var containerId string

		resp, httpRes, err := apiClient.ContainersAPI.RestartContainer(context.Background(), id, containerId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ContainersAPIService StartContainer", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string
		var containerId string

		resp, httpRes, err := apiClient.ContainersAPI.StartContainer(context.Background(), id, containerId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ContainersAPIService StopContainer", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string
		var containerId string

		resp, httpRes, err := apiClient.ContainersAPI.StopContainer(context.Background(), id, containerId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ContainersAPIService UpdateContainer", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string
		var containerId string

		resp, httpRes, err := apiClient.ContainersAPI.UpdateContainer(context.Background(), id, containerId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
