/*
Arcane API

Modern Docker Management, Designed for Everyone

API version: 1.11.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arcane

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EnvironmentWithApiKey type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EnvironmentWithApiKey{}

// EnvironmentWithApiKey struct for EnvironmentWithApiKey
type EnvironmentWithApiKey struct {
	// API key for pairing (only shown once during creation)
	ApiKey interface{} `json:"apiKey,omitempty"`
	ApiUrl interface{} `json:"apiUrl"`
	Enabled interface{} `json:"enabled"`
	Id interface{} `json:"id"`
	Name interface{} `json:"name,omitempty"`
	Status interface{} `json:"status"`
}

type _EnvironmentWithApiKey EnvironmentWithApiKey

// NewEnvironmentWithApiKey instantiates a new EnvironmentWithApiKey object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnvironmentWithApiKey(apiUrl interface{}, enabled interface{}, id interface{}, status interface{}) *EnvironmentWithApiKey {
	this := EnvironmentWithApiKey{}
	this.ApiUrl = apiUrl
	this.Enabled = enabled
	this.Id = id
	this.Status = status
	return &this
}

// NewEnvironmentWithApiKeyWithDefaults instantiates a new EnvironmentWithApiKey object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnvironmentWithApiKeyWithDefaults() *EnvironmentWithApiKey {
	this := EnvironmentWithApiKey{}
	return &this
}

// GetApiKey returns the ApiKey field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EnvironmentWithApiKey) GetApiKey() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.ApiKey
}

// GetApiKeyOk returns a tuple with the ApiKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EnvironmentWithApiKey) GetApiKeyOk() (*interface{}, bool) {
	if o == nil || IsNil(o.ApiKey) {
		return nil, false
	}
	return &o.ApiKey, true
}

// HasApiKey returns a boolean if a field has been set.
func (o *EnvironmentWithApiKey) HasApiKey() bool {
	if o != nil && IsNil(o.ApiKey) {
		return true
	}

	return false
}

// SetApiKey gets a reference to the given interface{} and assigns it to the ApiKey field.
func (o *EnvironmentWithApiKey) SetApiKey(v interface{}) {
	o.ApiKey = v
}

// GetApiUrl returns the ApiUrl field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *EnvironmentWithApiKey) GetApiUrl() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.ApiUrl
}

// GetApiUrlOk returns a tuple with the ApiUrl field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EnvironmentWithApiKey) GetApiUrlOk() (*interface{}, bool) {
	if o == nil || IsNil(o.ApiUrl) {
		return nil, false
	}
	return &o.ApiUrl, true
}

// SetApiUrl sets field value
func (o *EnvironmentWithApiKey) SetApiUrl(v interface{}) {
	o.ApiUrl = v
}

// GetEnabled returns the Enabled field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *EnvironmentWithApiKey) GetEnabled() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EnvironmentWithApiKey) GetEnabledOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *EnvironmentWithApiKey) SetEnabled(v interface{}) {
	o.Enabled = v
}

// GetId returns the Id field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *EnvironmentWithApiKey) GetId() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EnvironmentWithApiKey) GetIdOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *EnvironmentWithApiKey) SetId(v interface{}) {
	o.Id = v
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EnvironmentWithApiKey) GetName() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EnvironmentWithApiKey) GetNameOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return &o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *EnvironmentWithApiKey) HasName() bool {
	if o != nil && IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given interface{} and assigns it to the Name field.
func (o *EnvironmentWithApiKey) SetName(v interface{}) {
	o.Name = v
}

// GetStatus returns the Status field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *EnvironmentWithApiKey) GetStatus() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EnvironmentWithApiKey) GetStatusOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *EnvironmentWithApiKey) SetStatus(v interface{}) {
	o.Status = v
}

func (o EnvironmentWithApiKey) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EnvironmentWithApiKey) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.ApiKey != nil {
		toSerialize["apiKey"] = o.ApiKey
	}
	if o.ApiUrl != nil {
		toSerialize["apiUrl"] = o.ApiUrl
	}
	if o.Enabled != nil {
		toSerialize["enabled"] = o.Enabled
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

func (o *EnvironmentWithApiKey) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"apiUrl",
		"enabled",
		"id",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEnvironmentWithApiKey := _EnvironmentWithApiKey{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEnvironmentWithApiKey)

	if err != nil {
		return err
	}

	*o = EnvironmentWithApiKey(varEnvironmentWithApiKey)

	return err
}

type NullableEnvironmentWithApiKey struct {
	value *EnvironmentWithApiKey
	isSet bool
}

func (v NullableEnvironmentWithApiKey) Get() *EnvironmentWithApiKey {
	return v.value
}

func (v *NullableEnvironmentWithApiKey) Set(val *EnvironmentWithApiKey) {
	v.value = val
	v.isSet = true
}

func (v NullableEnvironmentWithApiKey) IsSet() bool {
	return v.isSet
}

func (v *NullableEnvironmentWithApiKey) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnvironmentWithApiKey(val *EnvironmentWithApiKey) *NullableEnvironmentWithApiKey {
	return &NullableEnvironmentWithApiKey{value: val, isSet: true}
}

func (v NullableEnvironmentWithApiKey) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnvironmentWithApiKey) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


