/*
Arcane API

Modern Docker Management, Designed for Everyone

API version: 1.11.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arcane

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DockerSwarmPeer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DockerSwarmPeer{}

// DockerSwarmPeer struct for DockerSwarmPeer
type DockerSwarmPeer struct {
	Addr interface{} `json:"Addr"`
	NodeID interface{} `json:"NodeID"`
}

type _DockerSwarmPeer DockerSwarmPeer

// NewDockerSwarmPeer instantiates a new DockerSwarmPeer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDockerSwarmPeer(addr interface{}, nodeID interface{}) *DockerSwarmPeer {
	this := DockerSwarmPeer{}
	this.Addr = addr
	this.NodeID = nodeID
	return &this
}

// NewDockerSwarmPeerWithDefaults instantiates a new DockerSwarmPeer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDockerSwarmPeerWithDefaults() *DockerSwarmPeer {
	this := DockerSwarmPeer{}
	return &this
}

// GetAddr returns the Addr field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *DockerSwarmPeer) GetAddr() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Addr
}

// GetAddrOk returns a tuple with the Addr field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DockerSwarmPeer) GetAddrOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Addr) {
		return nil, false
	}
	return &o.Addr, true
}

// SetAddr sets field value
func (o *DockerSwarmPeer) SetAddr(v interface{}) {
	o.Addr = v
}

// GetNodeID returns the NodeID field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *DockerSwarmPeer) GetNodeID() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.NodeID
}

// GetNodeIDOk returns a tuple with the NodeID field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DockerSwarmPeer) GetNodeIDOk() (*interface{}, bool) {
	if o == nil || IsNil(o.NodeID) {
		return nil, false
	}
	return &o.NodeID, true
}

// SetNodeID sets field value
func (o *DockerSwarmPeer) SetNodeID(v interface{}) {
	o.NodeID = v
}

func (o DockerSwarmPeer) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DockerSwarmPeer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Addr != nil {
		toSerialize["Addr"] = o.Addr
	}
	if o.NodeID != nil {
		toSerialize["NodeID"] = o.NodeID
	}
	return toSerialize, nil
}

func (o *DockerSwarmPeer) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"Addr",
		"NodeID",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDockerSwarmPeer := _DockerSwarmPeer{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDockerSwarmPeer)

	if err != nil {
		return err
	}

	*o = DockerSwarmPeer(varDockerSwarmPeer)

	return err
}

type NullableDockerSwarmPeer struct {
	value *DockerSwarmPeer
	isSet bool
}

func (v NullableDockerSwarmPeer) Get() *DockerSwarmPeer {
	return v.value
}

func (v *NullableDockerSwarmPeer) Set(val *DockerSwarmPeer) {
	v.value = val
	v.isSet = true
}

func (v NullableDockerSwarmPeer) IsSet() bool {
	return v.isSet
}

func (v *NullableDockerSwarmPeer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDockerSwarmPeer(val *DockerSwarmPeer) *NullableDockerSwarmPeer {
	return &NullableDockerSwarmPeer{value: val, isSet: true}
}

func (v NullableDockerSwarmPeer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDockerSwarmPeer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


