/*
Arcane API

Modern Docker Management, Designed for Everyone

API version: 1.11.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arcane

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DockerRegistryIndexInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DockerRegistryIndexInfo{}

// DockerRegistryIndexInfo struct for DockerRegistryIndexInfo
type DockerRegistryIndexInfo struct {
	Mirrors interface{} `json:"Mirrors"`
	Name interface{} `json:"Name"`
	Official interface{} `json:"Official"`
	Secure interface{} `json:"Secure"`
}

type _DockerRegistryIndexInfo DockerRegistryIndexInfo

// NewDockerRegistryIndexInfo instantiates a new DockerRegistryIndexInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDockerRegistryIndexInfo(mirrors interface{}, name interface{}, official interface{}, secure interface{}) *DockerRegistryIndexInfo {
	this := DockerRegistryIndexInfo{}
	this.Mirrors = mirrors
	this.Name = name
	this.Official = official
	this.Secure = secure
	return &this
}

// NewDockerRegistryIndexInfoWithDefaults instantiates a new DockerRegistryIndexInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDockerRegistryIndexInfoWithDefaults() *DockerRegistryIndexInfo {
	this := DockerRegistryIndexInfo{}
	return &this
}

// GetMirrors returns the Mirrors field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *DockerRegistryIndexInfo) GetMirrors() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Mirrors
}

// GetMirrorsOk returns a tuple with the Mirrors field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DockerRegistryIndexInfo) GetMirrorsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Mirrors) {
		return nil, false
	}
	return &o.Mirrors, true
}

// SetMirrors sets field value
func (o *DockerRegistryIndexInfo) SetMirrors(v interface{}) {
	o.Mirrors = v
}

// GetName returns the Name field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *DockerRegistryIndexInfo) GetName() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DockerRegistryIndexInfo) GetNameOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *DockerRegistryIndexInfo) SetName(v interface{}) {
	o.Name = v
}

// GetOfficial returns the Official field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *DockerRegistryIndexInfo) GetOfficial() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Official
}

// GetOfficialOk returns a tuple with the Official field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DockerRegistryIndexInfo) GetOfficialOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Official) {
		return nil, false
	}
	return &o.Official, true
}

// SetOfficial sets field value
func (o *DockerRegistryIndexInfo) SetOfficial(v interface{}) {
	o.Official = v
}

// GetSecure returns the Secure field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *DockerRegistryIndexInfo) GetSecure() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Secure
}

// GetSecureOk returns a tuple with the Secure field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DockerRegistryIndexInfo) GetSecureOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Secure) {
		return nil, false
	}
	return &o.Secure, true
}

// SetSecure sets field value
func (o *DockerRegistryIndexInfo) SetSecure(v interface{}) {
	o.Secure = v
}

func (o DockerRegistryIndexInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DockerRegistryIndexInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Mirrors != nil {
		toSerialize["Mirrors"] = o.Mirrors
	}
	if o.Name != nil {
		toSerialize["Name"] = o.Name
	}
	if o.Official != nil {
		toSerialize["Official"] = o.Official
	}
	if o.Secure != nil {
		toSerialize["Secure"] = o.Secure
	}
	return toSerialize, nil
}

func (o *DockerRegistryIndexInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"Mirrors",
		"Name",
		"Official",
		"Secure",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDockerRegistryIndexInfo := _DockerRegistryIndexInfo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDockerRegistryIndexInfo)

	if err != nil {
		return err
	}

	*o = DockerRegistryIndexInfo(varDockerRegistryIndexInfo)

	return err
}

type NullableDockerRegistryIndexInfo struct {
	value *DockerRegistryIndexInfo
	isSet bool
}

func (v NullableDockerRegistryIndexInfo) Get() *DockerRegistryIndexInfo {
	return v.value
}

func (v *NullableDockerRegistryIndexInfo) Set(val *DockerRegistryIndexInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableDockerRegistryIndexInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableDockerRegistryIndexInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDockerRegistryIndexInfo(val *DockerRegistryIndexInfo) *NullableDockerRegistryIndexInfo {
	return &NullableDockerRegistryIndexInfo{value: val, isSet: true}
}

func (v NullableDockerRegistryIndexInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDockerRegistryIndexInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


