/*
Arcane API

Modern Docker Management, Designed for Everyone

API version: 1.11.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arcane

import (
	"encoding/json"
	"fmt"
)

// checks if the AutoUpdateRecord type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AutoUpdateRecord{}

// AutoUpdateRecord struct for AutoUpdateRecord
type AutoUpdateRecord struct {
	CreatedAt interface{} `json:"createdAt"`
	Details interface{} `json:"details,omitempty"`
	EndTime interface{} `json:"endTime,omitempty"`
	Error *string `json:"error,omitempty"`
	Id string `json:"id"`
	NewImageVersions interface{} `json:"newImageVersions,omitempty"`
	OldImageVersions interface{} `json:"oldImageVersions,omitempty"`
	ResourceId string `json:"resourceId"`
	ResourceName string `json:"resourceName"`
	ResourceType string `json:"resourceType"`
	StartTime interface{} `json:"startTime"`
	Status string `json:"status"`
	UpdateApplied interface{} `json:"updateApplied"`
	UpdateAvailable interface{} `json:"updateAvailable"`
	UpdatedAt interface{} `json:"updatedAt,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AutoUpdateRecord AutoUpdateRecord

// NewAutoUpdateRecord instantiates a new AutoUpdateRecord object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAutoUpdateRecord(createdAt interface{}, id string, resourceId string, resourceName string, resourceType string, startTime interface{}, status string, updateApplied interface{}, updateAvailable interface{}) *AutoUpdateRecord {
	this := AutoUpdateRecord{}
	this.CreatedAt = createdAt
	this.Id = id
	this.ResourceId = resourceId
	this.ResourceName = resourceName
	this.ResourceType = resourceType
	this.StartTime = startTime
	this.Status = status
	this.UpdateApplied = updateApplied
	this.UpdateAvailable = updateAvailable
	return &this
}

// NewAutoUpdateRecordWithDefaults instantiates a new AutoUpdateRecord object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAutoUpdateRecordWithDefaults() *AutoUpdateRecord {
	this := AutoUpdateRecord{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *AutoUpdateRecord) GetCreatedAt() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AutoUpdateRecord) GetCreatedAtOk() (*interface{}, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *AutoUpdateRecord) SetCreatedAt(v interface{}) {
	o.CreatedAt = v
}

// GetDetails returns the Details field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AutoUpdateRecord) GetDetails() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Details
}

// GetDetailsOk returns a tuple with the Details field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AutoUpdateRecord) GetDetailsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Details) {
		return nil, false
	}
	return &o.Details, true
}

// HasDetails returns a boolean if a field has been set.
func (o *AutoUpdateRecord) HasDetails() bool {
	if o != nil && IsNil(o.Details) {
		return true
	}

	return false
}

// SetDetails gets a reference to the given interface{} and assigns it to the Details field.
func (o *AutoUpdateRecord) SetDetails(v interface{}) {
	o.Details = v
}

// GetEndTime returns the EndTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AutoUpdateRecord) GetEndTime() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.EndTime
}

// GetEndTimeOk returns a tuple with the EndTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AutoUpdateRecord) GetEndTimeOk() (*interface{}, bool) {
	if o == nil || IsNil(o.EndTime) {
		return nil, false
	}
	return &o.EndTime, true
}

// HasEndTime returns a boolean if a field has been set.
func (o *AutoUpdateRecord) HasEndTime() bool {
	if o != nil && IsNil(o.EndTime) {
		return true
	}

	return false
}

// SetEndTime gets a reference to the given interface{} and assigns it to the EndTime field.
func (o *AutoUpdateRecord) SetEndTime(v interface{}) {
	o.EndTime = v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *AutoUpdateRecord) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AutoUpdateRecord) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *AutoUpdateRecord) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *AutoUpdateRecord) SetError(v string) {
	o.Error = &v
}

// GetId returns the Id field value
func (o *AutoUpdateRecord) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AutoUpdateRecord) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AutoUpdateRecord) SetId(v string) {
	o.Id = v
}

// GetNewImageVersions returns the NewImageVersions field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AutoUpdateRecord) GetNewImageVersions() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.NewImageVersions
}

// GetNewImageVersionsOk returns a tuple with the NewImageVersions field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AutoUpdateRecord) GetNewImageVersionsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.NewImageVersions) {
		return nil, false
	}
	return &o.NewImageVersions, true
}

// HasNewImageVersions returns a boolean if a field has been set.
func (o *AutoUpdateRecord) HasNewImageVersions() bool {
	if o != nil && IsNil(o.NewImageVersions) {
		return true
	}

	return false
}

// SetNewImageVersions gets a reference to the given interface{} and assigns it to the NewImageVersions field.
func (o *AutoUpdateRecord) SetNewImageVersions(v interface{}) {
	o.NewImageVersions = v
}

// GetOldImageVersions returns the OldImageVersions field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AutoUpdateRecord) GetOldImageVersions() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.OldImageVersions
}

// GetOldImageVersionsOk returns a tuple with the OldImageVersions field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AutoUpdateRecord) GetOldImageVersionsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.OldImageVersions) {
		return nil, false
	}
	return &o.OldImageVersions, true
}

// HasOldImageVersions returns a boolean if a field has been set.
func (o *AutoUpdateRecord) HasOldImageVersions() bool {
	if o != nil && IsNil(o.OldImageVersions) {
		return true
	}

	return false
}

// SetOldImageVersions gets a reference to the given interface{} and assigns it to the OldImageVersions field.
func (o *AutoUpdateRecord) SetOldImageVersions(v interface{}) {
	o.OldImageVersions = v
}

// GetResourceId returns the ResourceId field value
func (o *AutoUpdateRecord) GetResourceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResourceId
}

// GetResourceIdOk returns a tuple with the ResourceId field value
// and a boolean to check if the value has been set.
func (o *AutoUpdateRecord) GetResourceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResourceId, true
}

// SetResourceId sets field value
func (o *AutoUpdateRecord) SetResourceId(v string) {
	o.ResourceId = v
}

// GetResourceName returns the ResourceName field value
func (o *AutoUpdateRecord) GetResourceName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResourceName
}

// GetResourceNameOk returns a tuple with the ResourceName field value
// and a boolean to check if the value has been set.
func (o *AutoUpdateRecord) GetResourceNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResourceName, true
}

// SetResourceName sets field value
func (o *AutoUpdateRecord) SetResourceName(v string) {
	o.ResourceName = v
}

// GetResourceType returns the ResourceType field value
func (o *AutoUpdateRecord) GetResourceType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResourceType
}

// GetResourceTypeOk returns a tuple with the ResourceType field value
// and a boolean to check if the value has been set.
func (o *AutoUpdateRecord) GetResourceTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResourceType, true
}

// SetResourceType sets field value
func (o *AutoUpdateRecord) SetResourceType(v string) {
	o.ResourceType = v
}

// GetStartTime returns the StartTime field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *AutoUpdateRecord) GetStartTime() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.StartTime
}

// GetStartTimeOk returns a tuple with the StartTime field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AutoUpdateRecord) GetStartTimeOk() (*interface{}, bool) {
	if o == nil || IsNil(o.StartTime) {
		return nil, false
	}
	return &o.StartTime, true
}

// SetStartTime sets field value
func (o *AutoUpdateRecord) SetStartTime(v interface{}) {
	o.StartTime = v
}

// GetStatus returns the Status field value
func (o *AutoUpdateRecord) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *AutoUpdateRecord) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *AutoUpdateRecord) SetStatus(v string) {
	o.Status = v
}

// GetUpdateApplied returns the UpdateApplied field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *AutoUpdateRecord) GetUpdateApplied() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.UpdateApplied
}

// GetUpdateAppliedOk returns a tuple with the UpdateApplied field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AutoUpdateRecord) GetUpdateAppliedOk() (*interface{}, bool) {
	if o == nil || IsNil(o.UpdateApplied) {
		return nil, false
	}
	return &o.UpdateApplied, true
}

// SetUpdateApplied sets field value
func (o *AutoUpdateRecord) SetUpdateApplied(v interface{}) {
	o.UpdateApplied = v
}

// GetUpdateAvailable returns the UpdateAvailable field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *AutoUpdateRecord) GetUpdateAvailable() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.UpdateAvailable
}

// GetUpdateAvailableOk returns a tuple with the UpdateAvailable field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AutoUpdateRecord) GetUpdateAvailableOk() (*interface{}, bool) {
	if o == nil || IsNil(o.UpdateAvailable) {
		return nil, false
	}
	return &o.UpdateAvailable, true
}

// SetUpdateAvailable sets field value
func (o *AutoUpdateRecord) SetUpdateAvailable(v interface{}) {
	o.UpdateAvailable = v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AutoUpdateRecord) GetUpdatedAt() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AutoUpdateRecord) GetUpdatedAtOk() (*interface{}, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *AutoUpdateRecord) HasUpdatedAt() bool {
	if o != nil && IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given interface{} and assigns it to the UpdatedAt field.
func (o *AutoUpdateRecord) SetUpdatedAt(v interface{}) {
	o.UpdatedAt = v
}

func (o AutoUpdateRecord) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AutoUpdateRecord) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.CreatedAt != nil {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if o.Details != nil {
		toSerialize["details"] = o.Details
	}
	if o.EndTime != nil {
		toSerialize["endTime"] = o.EndTime
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	toSerialize["id"] = o.Id
	if o.NewImageVersions != nil {
		toSerialize["newImageVersions"] = o.NewImageVersions
	}
	if o.OldImageVersions != nil {
		toSerialize["oldImageVersions"] = o.OldImageVersions
	}
	toSerialize["resourceId"] = o.ResourceId
	toSerialize["resourceName"] = o.ResourceName
	toSerialize["resourceType"] = o.ResourceType
	if o.StartTime != nil {
		toSerialize["startTime"] = o.StartTime
	}
	toSerialize["status"] = o.Status
	if o.UpdateApplied != nil {
		toSerialize["updateApplied"] = o.UpdateApplied
	}
	if o.UpdateAvailable != nil {
		toSerialize["updateAvailable"] = o.UpdateAvailable
	}
	if o.UpdatedAt != nil {
		toSerialize["updatedAt"] = o.UpdatedAt
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AutoUpdateRecord) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"createdAt",
		"id",
		"resourceId",
		"resourceName",
		"resourceType",
		"startTime",
		"status",
		"updateApplied",
		"updateAvailable",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAutoUpdateRecord := _AutoUpdateRecord{}

	err = json.Unmarshal(data, &varAutoUpdateRecord)

	if err != nil {
		return err
	}

	*o = AutoUpdateRecord(varAutoUpdateRecord)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "details")
		delete(additionalProperties, "endTime")
		delete(additionalProperties, "error")
		delete(additionalProperties, "id")
		delete(additionalProperties, "newImageVersions")
		delete(additionalProperties, "oldImageVersions")
		delete(additionalProperties, "resourceId")
		delete(additionalProperties, "resourceName")
		delete(additionalProperties, "resourceType")
		delete(additionalProperties, "startTime")
		delete(additionalProperties, "status")
		delete(additionalProperties, "updateApplied")
		delete(additionalProperties, "updateAvailable")
		delete(additionalProperties, "updatedAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAutoUpdateRecord struct {
	value *AutoUpdateRecord
	isSet bool
}

func (v NullableAutoUpdateRecord) Get() *AutoUpdateRecord {
	return v.value
}

func (v *NullableAutoUpdateRecord) Set(val *AutoUpdateRecord) {
	v.value = val
	v.isSet = true
}

func (v NullableAutoUpdateRecord) IsSet() bool {
	return v.isSet
}

func (v *NullableAutoUpdateRecord) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAutoUpdateRecord(val *AutoUpdateRecord) *NullableAutoUpdateRecord {
	return &NullableAutoUpdateRecord{value: val, isSet: true}
}

func (v NullableAutoUpdateRecord) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAutoUpdateRecord) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


