/*
Arcane API

Modern Docker Management, Designed for Everyone

API version: 1.11.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arcane

import (
	"encoding/json"
)

// checks if the NetworkCreateOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NetworkCreateOptions{}

// NetworkCreateOptions struct for NetworkCreateOptions
type NetworkCreateOptions struct {
	// Allow manual container attachment
	Attachable interface{} `json:"attachable,omitempty"`
	// Check for duplicate network names
	CheckDuplicate interface{} `json:"checkDuplicate,omitempty"`
	// Network driver (e.g., bridge, overlay)
	Driver interface{} `json:"driver,omitempty"`
	// Enable IPv6 networking
	EnableIPv6 interface{} `json:"enableIPv6,omitempty"`
	// Enable routing-mesh for swarm cluster
	Ingress interface{} `json:"ingress,omitempty"`
	// Restrict external access to the network
	Internal interface{} `json:"internal,omitempty"`
	// IP Address Management configuration
	Ipam *NetworkIPAM `json:"ipam,omitempty"`
	// User-defined labels
	Labels map[string]interface{} `json:"labels,omitempty"`
	// Driver-specific options
	Options map[string]interface{} `json:"options,omitempty"`
}

// NewNetworkCreateOptions instantiates a new NetworkCreateOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNetworkCreateOptions() *NetworkCreateOptions {
	this := NetworkCreateOptions{}
	return &this
}

// NewNetworkCreateOptionsWithDefaults instantiates a new NetworkCreateOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNetworkCreateOptionsWithDefaults() *NetworkCreateOptions {
	this := NetworkCreateOptions{}
	return &this
}

// GetAttachable returns the Attachable field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NetworkCreateOptions) GetAttachable() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Attachable
}

// GetAttachableOk returns a tuple with the Attachable field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NetworkCreateOptions) GetAttachableOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Attachable) {
		return nil, false
	}
	return &o.Attachable, true
}

// HasAttachable returns a boolean if a field has been set.
func (o *NetworkCreateOptions) HasAttachable() bool {
	if o != nil && IsNil(o.Attachable) {
		return true
	}

	return false
}

// SetAttachable gets a reference to the given interface{} and assigns it to the Attachable field.
func (o *NetworkCreateOptions) SetAttachable(v interface{}) {
	o.Attachable = v
}

// GetCheckDuplicate returns the CheckDuplicate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NetworkCreateOptions) GetCheckDuplicate() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.CheckDuplicate
}

// GetCheckDuplicateOk returns a tuple with the CheckDuplicate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NetworkCreateOptions) GetCheckDuplicateOk() (*interface{}, bool) {
	if o == nil || IsNil(o.CheckDuplicate) {
		return nil, false
	}
	return &o.CheckDuplicate, true
}

// HasCheckDuplicate returns a boolean if a field has been set.
func (o *NetworkCreateOptions) HasCheckDuplicate() bool {
	if o != nil && IsNil(o.CheckDuplicate) {
		return true
	}

	return false
}

// SetCheckDuplicate gets a reference to the given interface{} and assigns it to the CheckDuplicate field.
func (o *NetworkCreateOptions) SetCheckDuplicate(v interface{}) {
	o.CheckDuplicate = v
}

// GetDriver returns the Driver field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NetworkCreateOptions) GetDriver() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Driver
}

// GetDriverOk returns a tuple with the Driver field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NetworkCreateOptions) GetDriverOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Driver) {
		return nil, false
	}
	return &o.Driver, true
}

// HasDriver returns a boolean if a field has been set.
func (o *NetworkCreateOptions) HasDriver() bool {
	if o != nil && IsNil(o.Driver) {
		return true
	}

	return false
}

// SetDriver gets a reference to the given interface{} and assigns it to the Driver field.
func (o *NetworkCreateOptions) SetDriver(v interface{}) {
	o.Driver = v
}

// GetEnableIPv6 returns the EnableIPv6 field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NetworkCreateOptions) GetEnableIPv6() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.EnableIPv6
}

// GetEnableIPv6Ok returns a tuple with the EnableIPv6 field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NetworkCreateOptions) GetEnableIPv6Ok() (*interface{}, bool) {
	if o == nil || IsNil(o.EnableIPv6) {
		return nil, false
	}
	return &o.EnableIPv6, true
}

// HasEnableIPv6 returns a boolean if a field has been set.
func (o *NetworkCreateOptions) HasEnableIPv6() bool {
	if o != nil && IsNil(o.EnableIPv6) {
		return true
	}

	return false
}

// SetEnableIPv6 gets a reference to the given interface{} and assigns it to the EnableIPv6 field.
func (o *NetworkCreateOptions) SetEnableIPv6(v interface{}) {
	o.EnableIPv6 = v
}

// GetIngress returns the Ingress field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NetworkCreateOptions) GetIngress() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Ingress
}

// GetIngressOk returns a tuple with the Ingress field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NetworkCreateOptions) GetIngressOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Ingress) {
		return nil, false
	}
	return &o.Ingress, true
}

// HasIngress returns a boolean if a field has been set.
func (o *NetworkCreateOptions) HasIngress() bool {
	if o != nil && IsNil(o.Ingress) {
		return true
	}

	return false
}

// SetIngress gets a reference to the given interface{} and assigns it to the Ingress field.
func (o *NetworkCreateOptions) SetIngress(v interface{}) {
	o.Ingress = v
}

// GetInternal returns the Internal field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NetworkCreateOptions) GetInternal() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Internal
}

// GetInternalOk returns a tuple with the Internal field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NetworkCreateOptions) GetInternalOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Internal) {
		return nil, false
	}
	return &o.Internal, true
}

// HasInternal returns a boolean if a field has been set.
func (o *NetworkCreateOptions) HasInternal() bool {
	if o != nil && IsNil(o.Internal) {
		return true
	}

	return false
}

// SetInternal gets a reference to the given interface{} and assigns it to the Internal field.
func (o *NetworkCreateOptions) SetInternal(v interface{}) {
	o.Internal = v
}

// GetIpam returns the Ipam field value if set, zero value otherwise.
func (o *NetworkCreateOptions) GetIpam() NetworkIPAM {
	if o == nil || IsNil(o.Ipam) {
		var ret NetworkIPAM
		return ret
	}
	return *o.Ipam
}

// GetIpamOk returns a tuple with the Ipam field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkCreateOptions) GetIpamOk() (*NetworkIPAM, bool) {
	if o == nil || IsNil(o.Ipam) {
		return nil, false
	}
	return o.Ipam, true
}

// HasIpam returns a boolean if a field has been set.
func (o *NetworkCreateOptions) HasIpam() bool {
	if o != nil && !IsNil(o.Ipam) {
		return true
	}

	return false
}

// SetIpam gets a reference to the given NetworkIPAM and assigns it to the Ipam field.
func (o *NetworkCreateOptions) SetIpam(v NetworkIPAM) {
	o.Ipam = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NetworkCreateOptions) GetLabels() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NetworkCreateOptions) GetLabelsOk() (*map[string]interface{}, bool) {
	if o == nil || IsNil(o.Labels) {
		return nil, false
	}
	return &o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *NetworkCreateOptions) HasLabels() bool {
	if o != nil && IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]interface{} and assigns it to the Labels field.
func (o *NetworkCreateOptions) SetLabels(v map[string]interface{}) {
	o.Labels = v
}

// GetOptions returns the Options field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NetworkCreateOptions) GetOptions() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Options
}

// GetOptionsOk returns a tuple with the Options field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NetworkCreateOptions) GetOptionsOk() (*map[string]interface{}, bool) {
	if o == nil || IsNil(o.Options) {
		return nil, false
	}
	return &o.Options, true
}

// HasOptions returns a boolean if a field has been set.
func (o *NetworkCreateOptions) HasOptions() bool {
	if o != nil && IsNil(o.Options) {
		return true
	}

	return false
}

// SetOptions gets a reference to the given map[string]interface{} and assigns it to the Options field.
func (o *NetworkCreateOptions) SetOptions(v map[string]interface{}) {
	o.Options = v
}

func (o NetworkCreateOptions) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NetworkCreateOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Attachable != nil {
		toSerialize["attachable"] = o.Attachable
	}
	if o.CheckDuplicate != nil {
		toSerialize["checkDuplicate"] = o.CheckDuplicate
	}
	if o.Driver != nil {
		toSerialize["driver"] = o.Driver
	}
	if o.EnableIPv6 != nil {
		toSerialize["enableIPv6"] = o.EnableIPv6
	}
	if o.Ingress != nil {
		toSerialize["ingress"] = o.Ingress
	}
	if o.Internal != nil {
		toSerialize["internal"] = o.Internal
	}
	if !IsNil(o.Ipam) {
		toSerialize["ipam"] = o.Ipam
	}
	if o.Labels != nil {
		toSerialize["labels"] = o.Labels
	}
	if o.Options != nil {
		toSerialize["options"] = o.Options
	}
	return toSerialize, nil
}

type NullableNetworkCreateOptions struct {
	value *NetworkCreateOptions
	isSet bool
}

func (v NullableNetworkCreateOptions) Get() *NetworkCreateOptions {
	return v.value
}

func (v *NullableNetworkCreateOptions) Set(val *NetworkCreateOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableNetworkCreateOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableNetworkCreateOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetworkCreateOptions(val *NetworkCreateOptions) *NullableNetworkCreateOptions {
	return &NullableNetworkCreateOptions{value: val, isSet: true}
}

func (v NullableNetworkCreateOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetworkCreateOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


