/*
Arcane API

Modern Docker Management, Designed for Everyone

API version: 1.11.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arcane

import (
	"encoding/json"
)

// checks if the DockerTypesDeviceMapping type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DockerTypesDeviceMapping{}

// DockerTypesDeviceMapping struct for DockerTypesDeviceMapping
type DockerTypesDeviceMapping struct {
	Permissions interface{} `json:"permissions,omitempty"`
	Source interface{} `json:"source,omitempty"`
	Target interface{} `json:"target,omitempty"`
}

// NewDockerTypesDeviceMapping instantiates a new DockerTypesDeviceMapping object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDockerTypesDeviceMapping() *DockerTypesDeviceMapping {
	this := DockerTypesDeviceMapping{}
	return &this
}

// NewDockerTypesDeviceMappingWithDefaults instantiates a new DockerTypesDeviceMapping object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDockerTypesDeviceMappingWithDefaults() *DockerTypesDeviceMapping {
	this := DockerTypesDeviceMapping{}
	return &this
}

// GetPermissions returns the Permissions field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DockerTypesDeviceMapping) GetPermissions() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Permissions
}

// GetPermissionsOk returns a tuple with the Permissions field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DockerTypesDeviceMapping) GetPermissionsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Permissions) {
		return nil, false
	}
	return &o.Permissions, true
}

// HasPermissions returns a boolean if a field has been set.
func (o *DockerTypesDeviceMapping) HasPermissions() bool {
	if o != nil && IsNil(o.Permissions) {
		return true
	}

	return false
}

// SetPermissions gets a reference to the given interface{} and assigns it to the Permissions field.
func (o *DockerTypesDeviceMapping) SetPermissions(v interface{}) {
	o.Permissions = v
}

// GetSource returns the Source field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DockerTypesDeviceMapping) GetSource() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DockerTypesDeviceMapping) GetSourceOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Source) {
		return nil, false
	}
	return &o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *DockerTypesDeviceMapping) HasSource() bool {
	if o != nil && IsNil(o.Source) {
		return true
	}

	return false
}

// SetSource gets a reference to the given interface{} and assigns it to the Source field.
func (o *DockerTypesDeviceMapping) SetSource(v interface{}) {
	o.Source = v
}

// GetTarget returns the Target field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DockerTypesDeviceMapping) GetTarget() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Target
}

// GetTargetOk returns a tuple with the Target field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DockerTypesDeviceMapping) GetTargetOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Target) {
		return nil, false
	}
	return &o.Target, true
}

// HasTarget returns a boolean if a field has been set.
func (o *DockerTypesDeviceMapping) HasTarget() bool {
	if o != nil && IsNil(o.Target) {
		return true
	}

	return false
}

// SetTarget gets a reference to the given interface{} and assigns it to the Target field.
func (o *DockerTypesDeviceMapping) SetTarget(v interface{}) {
	o.Target = v
}

func (o DockerTypesDeviceMapping) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DockerTypesDeviceMapping) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Permissions != nil {
		toSerialize["permissions"] = o.Permissions
	}
	if o.Source != nil {
		toSerialize["source"] = o.Source
	}
	if o.Target != nil {
		toSerialize["target"] = o.Target
	}
	return toSerialize, nil
}

type NullableDockerTypesDeviceMapping struct {
	value *DockerTypesDeviceMapping
	isSet bool
}

func (v NullableDockerTypesDeviceMapping) Get() *DockerTypesDeviceMapping {
	return v.value
}

func (v *NullableDockerTypesDeviceMapping) Set(val *DockerTypesDeviceMapping) {
	v.value = val
	v.isSet = true
}

func (v NullableDockerTypesDeviceMapping) IsSet() bool {
	return v.isSet
}

func (v *NullableDockerTypesDeviceMapping) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDockerTypesDeviceMapping(val *DockerTypesDeviceMapping) *NullableDockerTypesDeviceMapping {
	return &NullableDockerTypesDeviceMapping{value: val, isSet: true}
}

func (v NullableDockerTypesDeviceMapping) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDockerTypesDeviceMapping) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


