/*
Arcane API

Modern Docker Management, Designed for Everyone

API version: 1.11.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arcane

import (
	"encoding/json"
)

// checks if the ProjectDestroy type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectDestroy{}

// ProjectDestroy struct for ProjectDestroy
type ProjectDestroy struct {
	// A URL to the JSON Schema for this object.
	Schema interface{} `json:"$schema,omitempty"`
	RemoveFiles interface{} `json:"removeFiles,omitempty"`
	RemoveVolumes interface{} `json:"removeVolumes,omitempty"`
}

// NewProjectDestroy instantiates a new ProjectDestroy object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectDestroy() *ProjectDestroy {
	this := ProjectDestroy{}
	return &this
}

// NewProjectDestroyWithDefaults instantiates a new ProjectDestroy object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectDestroyWithDefaults() *ProjectDestroy {
	this := ProjectDestroy{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProjectDestroy) GetSchema() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProjectDestroy) GetSchemaOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return &o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *ProjectDestroy) HasSchema() bool {
	if o != nil && IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given interface{} and assigns it to the Schema field.
func (o *ProjectDestroy) SetSchema(v interface{}) {
	o.Schema = v
}

// GetRemoveFiles returns the RemoveFiles field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProjectDestroy) GetRemoveFiles() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.RemoveFiles
}

// GetRemoveFilesOk returns a tuple with the RemoveFiles field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProjectDestroy) GetRemoveFilesOk() (*interface{}, bool) {
	if o == nil || IsNil(o.RemoveFiles) {
		return nil, false
	}
	return &o.RemoveFiles, true
}

// HasRemoveFiles returns a boolean if a field has been set.
func (o *ProjectDestroy) HasRemoveFiles() bool {
	if o != nil && IsNil(o.RemoveFiles) {
		return true
	}

	return false
}

// SetRemoveFiles gets a reference to the given interface{} and assigns it to the RemoveFiles field.
func (o *ProjectDestroy) SetRemoveFiles(v interface{}) {
	o.RemoveFiles = v
}

// GetRemoveVolumes returns the RemoveVolumes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProjectDestroy) GetRemoveVolumes() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.RemoveVolumes
}

// GetRemoveVolumesOk returns a tuple with the RemoveVolumes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProjectDestroy) GetRemoveVolumesOk() (*interface{}, bool) {
	if o == nil || IsNil(o.RemoveVolumes) {
		return nil, false
	}
	return &o.RemoveVolumes, true
}

// HasRemoveVolumes returns a boolean if a field has been set.
func (o *ProjectDestroy) HasRemoveVolumes() bool {
	if o != nil && IsNil(o.RemoveVolumes) {
		return true
	}

	return false
}

// SetRemoveVolumes gets a reference to the given interface{} and assigns it to the RemoveVolumes field.
func (o *ProjectDestroy) SetRemoveVolumes(v interface{}) {
	o.RemoveVolumes = v
}

func (o ProjectDestroy) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectDestroy) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Schema != nil {
		toSerialize["$schema"] = o.Schema
	}
	if o.RemoveFiles != nil {
		toSerialize["removeFiles"] = o.RemoveFiles
	}
	if o.RemoveVolumes != nil {
		toSerialize["removeVolumes"] = o.RemoveVolumes
	}
	return toSerialize, nil
}

type NullableProjectDestroy struct {
	value *ProjectDestroy
	isSet bool
}

func (v NullableProjectDestroy) Get() *ProjectDestroy {
	return v.value
}

func (v *NullableProjectDestroy) Set(val *ProjectDestroy) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectDestroy) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectDestroy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectDestroy(val *ProjectDestroy) *NullableProjectDestroy {
	return &NullableProjectDestroy{value: val, isSet: true}
}

func (v NullableProjectDestroy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectDestroy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


