/*
Arcane API

Modern Docker Management, Designed for Everyone

API version: 1.11.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arcane

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VersionCheck type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VersionCheck{}

// VersionCheck struct for VersionCheck
type VersionCheck struct {
	// A URL to the JSON Schema for this object.
	Schema interface{} `json:"$schema,omitempty"`
	CurrentVersion interface{} `json:"currentVersion"`
	NewestVersion interface{} `json:"newestVersion,omitempty"`
	ReleaseUrl interface{} `json:"releaseUrl,omitempty"`
	UpdateAvailable interface{} `json:"updateAvailable"`
}

type _VersionCheck VersionCheck

// NewVersionCheck instantiates a new VersionCheck object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVersionCheck(currentVersion interface{}, updateAvailable interface{}) *VersionCheck {
	this := VersionCheck{}
	this.CurrentVersion = currentVersion
	this.UpdateAvailable = updateAvailable
	return &this
}

// NewVersionCheckWithDefaults instantiates a new VersionCheck object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVersionCheckWithDefaults() *VersionCheck {
	this := VersionCheck{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VersionCheck) GetSchema() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VersionCheck) GetSchemaOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return &o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *VersionCheck) HasSchema() bool {
	if o != nil && IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given interface{} and assigns it to the Schema field.
func (o *VersionCheck) SetSchema(v interface{}) {
	o.Schema = v
}

// GetCurrentVersion returns the CurrentVersion field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *VersionCheck) GetCurrentVersion() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.CurrentVersion
}

// GetCurrentVersionOk returns a tuple with the CurrentVersion field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VersionCheck) GetCurrentVersionOk() (*interface{}, bool) {
	if o == nil || IsNil(o.CurrentVersion) {
		return nil, false
	}
	return &o.CurrentVersion, true
}

// SetCurrentVersion sets field value
func (o *VersionCheck) SetCurrentVersion(v interface{}) {
	o.CurrentVersion = v
}

// GetNewestVersion returns the NewestVersion field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VersionCheck) GetNewestVersion() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.NewestVersion
}

// GetNewestVersionOk returns a tuple with the NewestVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VersionCheck) GetNewestVersionOk() (*interface{}, bool) {
	if o == nil || IsNil(o.NewestVersion) {
		return nil, false
	}
	return &o.NewestVersion, true
}

// HasNewestVersion returns a boolean if a field has been set.
func (o *VersionCheck) HasNewestVersion() bool {
	if o != nil && IsNil(o.NewestVersion) {
		return true
	}

	return false
}

// SetNewestVersion gets a reference to the given interface{} and assigns it to the NewestVersion field.
func (o *VersionCheck) SetNewestVersion(v interface{}) {
	o.NewestVersion = v
}

// GetReleaseUrl returns the ReleaseUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VersionCheck) GetReleaseUrl() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.ReleaseUrl
}

// GetReleaseUrlOk returns a tuple with the ReleaseUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VersionCheck) GetReleaseUrlOk() (*interface{}, bool) {
	if o == nil || IsNil(o.ReleaseUrl) {
		return nil, false
	}
	return &o.ReleaseUrl, true
}

// HasReleaseUrl returns a boolean if a field has been set.
func (o *VersionCheck) HasReleaseUrl() bool {
	if o != nil && IsNil(o.ReleaseUrl) {
		return true
	}

	return false
}

// SetReleaseUrl gets a reference to the given interface{} and assigns it to the ReleaseUrl field.
func (o *VersionCheck) SetReleaseUrl(v interface{}) {
	o.ReleaseUrl = v
}

// GetUpdateAvailable returns the UpdateAvailable field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *VersionCheck) GetUpdateAvailable() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.UpdateAvailable
}

// GetUpdateAvailableOk returns a tuple with the UpdateAvailable field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VersionCheck) GetUpdateAvailableOk() (*interface{}, bool) {
	if o == nil || IsNil(o.UpdateAvailable) {
		return nil, false
	}
	return &o.UpdateAvailable, true
}

// SetUpdateAvailable sets field value
func (o *VersionCheck) SetUpdateAvailable(v interface{}) {
	o.UpdateAvailable = v
}

func (o VersionCheck) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VersionCheck) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Schema != nil {
		toSerialize["$schema"] = o.Schema
	}
	if o.CurrentVersion != nil {
		toSerialize["currentVersion"] = o.CurrentVersion
	}
	if o.NewestVersion != nil {
		toSerialize["newestVersion"] = o.NewestVersion
	}
	if o.ReleaseUrl != nil {
		toSerialize["releaseUrl"] = o.ReleaseUrl
	}
	if o.UpdateAvailable != nil {
		toSerialize["updateAvailable"] = o.UpdateAvailable
	}
	return toSerialize, nil
}

func (o *VersionCheck) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"currentVersion",
		"updateAvailable",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVersionCheck := _VersionCheck{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVersionCheck)

	if err != nil {
		return err
	}

	*o = VersionCheck(varVersionCheck)

	return err
}

type NullableVersionCheck struct {
	value *VersionCheck
	isSet bool
}

func (v NullableVersionCheck) Get() *VersionCheck {
	return v.value
}

func (v *NullableVersionCheck) Set(val *VersionCheck) {
	v.value = val
	v.isSet = true
}

func (v NullableVersionCheck) IsSet() bool {
	return v.isSet
}

func (v *NullableVersionCheck) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVersionCheck(val *VersionCheck) *NullableVersionCheck {
	return &NullableVersionCheck{value: val, isSet: true}
}

func (v NullableVersionCheck) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVersionCheck) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


