/*
Arcane API

Modern Docker Management, Designed for Everyone

API version: 1.11.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arcane

import (
	"encoding/json"
)

// checks if the DockerSwarmVersion type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DockerSwarmVersion{}

// DockerSwarmVersion struct for DockerSwarmVersion
type DockerSwarmVersion struct {
	Index interface{} `json:"Index,omitempty"`
}

// NewDockerSwarmVersion instantiates a new DockerSwarmVersion object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDockerSwarmVersion() *DockerSwarmVersion {
	this := DockerSwarmVersion{}
	return &this
}

// NewDockerSwarmVersionWithDefaults instantiates a new DockerSwarmVersion object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDockerSwarmVersionWithDefaults() *DockerSwarmVersion {
	this := DockerSwarmVersion{}
	return &this
}

// GetIndex returns the Index field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DockerSwarmVersion) GetIndex() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Index
}

// GetIndexOk returns a tuple with the Index field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DockerSwarmVersion) GetIndexOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Index) {
		return nil, false
	}
	return &o.Index, true
}

// HasIndex returns a boolean if a field has been set.
func (o *DockerSwarmVersion) HasIndex() bool {
	if o != nil && IsNil(o.Index) {
		return true
	}

	return false
}

// SetIndex gets a reference to the given interface{} and assigns it to the Index field.
func (o *DockerSwarmVersion) SetIndex(v interface{}) {
	o.Index = v
}

func (o DockerSwarmVersion) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DockerSwarmVersion) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Index != nil {
		toSerialize["Index"] = o.Index
	}
	return toSerialize, nil
}

type NullableDockerSwarmVersion struct {
	value *DockerSwarmVersion
	isSet bool
}

func (v NullableDockerSwarmVersion) Get() *DockerSwarmVersion {
	return v.value
}

func (v *NullableDockerSwarmVersion) Set(val *DockerSwarmVersion) {
	v.value = val
	v.isSet = true
}

func (v NullableDockerSwarmVersion) IsSet() bool {
	return v.isSet
}

func (v *NullableDockerSwarmVersion) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDockerSwarmVersion(val *DockerSwarmVersion) *NullableDockerSwarmVersion {
	return &NullableDockerSwarmVersion{value: val, isSet: true}
}

func (v NullableDockerSwarmVersion) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDockerSwarmVersion) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


