/*
Arcane API

Modern Docker Management, Designed for Everyone

API version: 1.11.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arcane

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ImagePruneReport type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ImagePruneReport{}

// ImagePruneReport struct for ImagePruneReport
type ImagePruneReport struct {
	ImagesDeleted interface{} `json:"imagesDeleted"`
	SpaceReclaimed interface{} `json:"spaceReclaimed"`
}

type _ImagePruneReport ImagePruneReport

// NewImagePruneReport instantiates a new ImagePruneReport object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImagePruneReport(imagesDeleted interface{}, spaceReclaimed interface{}) *ImagePruneReport {
	this := ImagePruneReport{}
	this.ImagesDeleted = imagesDeleted
	this.SpaceReclaimed = spaceReclaimed
	return &this
}

// NewImagePruneReportWithDefaults instantiates a new ImagePruneReport object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImagePruneReportWithDefaults() *ImagePruneReport {
	this := ImagePruneReport{}
	return &this
}

// GetImagesDeleted returns the ImagesDeleted field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *ImagePruneReport) GetImagesDeleted() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.ImagesDeleted
}

// GetImagesDeletedOk returns a tuple with the ImagesDeleted field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ImagePruneReport) GetImagesDeletedOk() (*interface{}, bool) {
	if o == nil || IsNil(o.ImagesDeleted) {
		return nil, false
	}
	return &o.ImagesDeleted, true
}

// SetImagesDeleted sets field value
func (o *ImagePruneReport) SetImagesDeleted(v interface{}) {
	o.ImagesDeleted = v
}

// GetSpaceReclaimed returns the SpaceReclaimed field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *ImagePruneReport) GetSpaceReclaimed() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.SpaceReclaimed
}

// GetSpaceReclaimedOk returns a tuple with the SpaceReclaimed field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ImagePruneReport) GetSpaceReclaimedOk() (*interface{}, bool) {
	if o == nil || IsNil(o.SpaceReclaimed) {
		return nil, false
	}
	return &o.SpaceReclaimed, true
}

// SetSpaceReclaimed sets field value
func (o *ImagePruneReport) SetSpaceReclaimed(v interface{}) {
	o.SpaceReclaimed = v
}

func (o ImagePruneReport) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ImagePruneReport) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.ImagesDeleted != nil {
		toSerialize["imagesDeleted"] = o.ImagesDeleted
	}
	if o.SpaceReclaimed != nil {
		toSerialize["spaceReclaimed"] = o.SpaceReclaimed
	}
	return toSerialize, nil
}

func (o *ImagePruneReport) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"imagesDeleted",
		"spaceReclaimed",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varImagePruneReport := _ImagePruneReport{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varImagePruneReport)

	if err != nil {
		return err
	}

	*o = ImagePruneReport(varImagePruneReport)

	return err
}

type NullableImagePruneReport struct {
	value *ImagePruneReport
	isSet bool
}

func (v NullableImagePruneReport) Get() *ImagePruneReport {
	return v.value
}

func (v *NullableImagePruneReport) Set(val *ImagePruneReport) {
	v.value = val
	v.isSet = true
}

func (v NullableImagePruneReport) IsSet() bool {
	return v.isSet
}

func (v *NullableImagePruneReport) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImagePruneReport(val *ImagePruneReport) *NullableImagePruneReport {
	return &NullableImagePruneReport{value: val, isSet: true}
}

func (v NullableImagePruneReport) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImagePruneReport) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


