/*
Arcane API

Modern Docker Management, Designed for Everyone

API version: 1.11.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arcane

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DockerTypesServiceHook type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DockerTypesServiceHook{}

// DockerTypesServiceHook struct for DockerTypesServiceHook
type DockerTypesServiceHook struct {
	Command interface{} `json:"command"`
	Environment map[string]interface{} `json:"environment,omitempty"`
	Privileged interface{} `json:"privileged,omitempty"`
	User interface{} `json:"user,omitempty"`
	WorkingDir interface{} `json:"working_dir,omitempty"`
}

type _DockerTypesServiceHook DockerTypesServiceHook

// NewDockerTypesServiceHook instantiates a new DockerTypesServiceHook object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDockerTypesServiceHook(command interface{}) *DockerTypesServiceHook {
	this := DockerTypesServiceHook{}
	this.Command = command
	return &this
}

// NewDockerTypesServiceHookWithDefaults instantiates a new DockerTypesServiceHook object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDockerTypesServiceHookWithDefaults() *DockerTypesServiceHook {
	this := DockerTypesServiceHook{}
	return &this
}

// GetCommand returns the Command field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *DockerTypesServiceHook) GetCommand() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Command
}

// GetCommandOk returns a tuple with the Command field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DockerTypesServiceHook) GetCommandOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Command) {
		return nil, false
	}
	return &o.Command, true
}

// SetCommand sets field value
func (o *DockerTypesServiceHook) SetCommand(v interface{}) {
	o.Command = v
}

// GetEnvironment returns the Environment field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DockerTypesServiceHook) GetEnvironment() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Environment
}

// GetEnvironmentOk returns a tuple with the Environment field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DockerTypesServiceHook) GetEnvironmentOk() (*map[string]interface{}, bool) {
	if o == nil || IsNil(o.Environment) {
		return nil, false
	}
	return &o.Environment, true
}

// HasEnvironment returns a boolean if a field has been set.
func (o *DockerTypesServiceHook) HasEnvironment() bool {
	if o != nil && IsNil(o.Environment) {
		return true
	}

	return false
}

// SetEnvironment gets a reference to the given map[string]interface{} and assigns it to the Environment field.
func (o *DockerTypesServiceHook) SetEnvironment(v map[string]interface{}) {
	o.Environment = v
}

// GetPrivileged returns the Privileged field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DockerTypesServiceHook) GetPrivileged() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Privileged
}

// GetPrivilegedOk returns a tuple with the Privileged field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DockerTypesServiceHook) GetPrivilegedOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Privileged) {
		return nil, false
	}
	return &o.Privileged, true
}

// HasPrivileged returns a boolean if a field has been set.
func (o *DockerTypesServiceHook) HasPrivileged() bool {
	if o != nil && IsNil(o.Privileged) {
		return true
	}

	return false
}

// SetPrivileged gets a reference to the given interface{} and assigns it to the Privileged field.
func (o *DockerTypesServiceHook) SetPrivileged(v interface{}) {
	o.Privileged = v
}

// GetUser returns the User field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DockerTypesServiceHook) GetUser() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DockerTypesServiceHook) GetUserOk() (*interface{}, bool) {
	if o == nil || IsNil(o.User) {
		return nil, false
	}
	return &o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *DockerTypesServiceHook) HasUser() bool {
	if o != nil && IsNil(o.User) {
		return true
	}

	return false
}

// SetUser gets a reference to the given interface{} and assigns it to the User field.
func (o *DockerTypesServiceHook) SetUser(v interface{}) {
	o.User = v
}

// GetWorkingDir returns the WorkingDir field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DockerTypesServiceHook) GetWorkingDir() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.WorkingDir
}

// GetWorkingDirOk returns a tuple with the WorkingDir field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DockerTypesServiceHook) GetWorkingDirOk() (*interface{}, bool) {
	if o == nil || IsNil(o.WorkingDir) {
		return nil, false
	}
	return &o.WorkingDir, true
}

// HasWorkingDir returns a boolean if a field has been set.
func (o *DockerTypesServiceHook) HasWorkingDir() bool {
	if o != nil && IsNil(o.WorkingDir) {
		return true
	}

	return false
}

// SetWorkingDir gets a reference to the given interface{} and assigns it to the WorkingDir field.
func (o *DockerTypesServiceHook) SetWorkingDir(v interface{}) {
	o.WorkingDir = v
}

func (o DockerTypesServiceHook) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DockerTypesServiceHook) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Command != nil {
		toSerialize["command"] = o.Command
	}
	if o.Environment != nil {
		toSerialize["environment"] = o.Environment
	}
	if o.Privileged != nil {
		toSerialize["privileged"] = o.Privileged
	}
	if o.User != nil {
		toSerialize["user"] = o.User
	}
	if o.WorkingDir != nil {
		toSerialize["working_dir"] = o.WorkingDir
	}
	return toSerialize, nil
}

func (o *DockerTypesServiceHook) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"command",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDockerTypesServiceHook := _DockerTypesServiceHook{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDockerTypesServiceHook)

	if err != nil {
		return err
	}

	*o = DockerTypesServiceHook(varDockerTypesServiceHook)

	return err
}

type NullableDockerTypesServiceHook struct {
	value *DockerTypesServiceHook
	isSet bool
}

func (v NullableDockerTypesServiceHook) Get() *DockerTypesServiceHook {
	return v.value
}

func (v *NullableDockerTypesServiceHook) Set(val *DockerTypesServiceHook) {
	v.value = val
	v.isSet = true
}

func (v NullableDockerTypesServiceHook) IsSet() bool {
	return v.isSet
}

func (v *NullableDockerTypesServiceHook) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDockerTypesServiceHook(val *DockerTypesServiceHook) *NullableDockerTypesServiceHook {
	return &NullableDockerTypesServiceHook{value: val, isSet: true}
}

func (v NullableDockerTypesServiceHook) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDockerTypesServiceHook) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


