/*
Arcane API

Modern Docker Management, Designed for Everyone

API version: 1.11.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arcane

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ContainerregistryCredential type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContainerregistryCredential{}

// ContainerregistryCredential struct for ContainerregistryCredential
type ContainerregistryCredential struct {
	Enabled interface{} `json:"enabled"`
	Token interface{} `json:"token"`
	Url interface{} `json:"url"`
	Username interface{} `json:"username"`
}

type _ContainerregistryCredential ContainerregistryCredential

// NewContainerregistryCredential instantiates a new ContainerregistryCredential object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContainerregistryCredential(enabled interface{}, token interface{}, url interface{}, username interface{}) *ContainerregistryCredential {
	this := ContainerregistryCredential{}
	this.Enabled = enabled
	this.Token = token
	this.Url = url
	this.Username = username
	return &this
}

// NewContainerregistryCredentialWithDefaults instantiates a new ContainerregistryCredential object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContainerregistryCredentialWithDefaults() *ContainerregistryCredential {
	this := ContainerregistryCredential{}
	return &this
}

// GetEnabled returns the Enabled field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *ContainerregistryCredential) GetEnabled() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ContainerregistryCredential) GetEnabledOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *ContainerregistryCredential) SetEnabled(v interface{}) {
	o.Enabled = v
}

// GetToken returns the Token field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *ContainerregistryCredential) GetToken() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ContainerregistryCredential) GetTokenOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Token) {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *ContainerregistryCredential) SetToken(v interface{}) {
	o.Token = v
}

// GetUrl returns the Url field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *ContainerregistryCredential) GetUrl() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ContainerregistryCredential) GetUrlOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *ContainerregistryCredential) SetUrl(v interface{}) {
	o.Url = v
}

// GetUsername returns the Username field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *ContainerregistryCredential) GetUsername() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ContainerregistryCredential) GetUsernameOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *ContainerregistryCredential) SetUsername(v interface{}) {
	o.Username = v
}

func (o ContainerregistryCredential) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContainerregistryCredential) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Enabled != nil {
		toSerialize["enabled"] = o.Enabled
	}
	if o.Token != nil {
		toSerialize["token"] = o.Token
	}
	if o.Url != nil {
		toSerialize["url"] = o.Url
	}
	if o.Username != nil {
		toSerialize["username"] = o.Username
	}
	return toSerialize, nil
}

func (o *ContainerregistryCredential) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"enabled",
		"token",
		"url",
		"username",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varContainerregistryCredential := _ContainerregistryCredential{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varContainerregistryCredential)

	if err != nil {
		return err
	}

	*o = ContainerregistryCredential(varContainerregistryCredential)

	return err
}

type NullableContainerregistryCredential struct {
	value *ContainerregistryCredential
	isSet bool
}

func (v NullableContainerregistryCredential) Get() *ContainerregistryCredential {
	return v.value
}

func (v *NullableContainerregistryCredential) Set(val *ContainerregistryCredential) {
	v.value = val
	v.isSet = true
}

func (v NullableContainerregistryCredential) IsSet() bool {
	return v.isSet
}

func (v *NullableContainerregistryCredential) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContainerregistryCredential(val *ContainerregistryCredential) *NullableContainerregistryCredential {
	return &NullableContainerregistryCredential{value: val, isSet: true}
}

func (v NullableContainerregistryCredential) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContainerregistryCredential) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


