/*
Arcane API

Modern Docker Management, Designed for Everyone

API version: 1.11.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arcane

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TemplateTemplateContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TemplateTemplateContent{}

// TemplateTemplateContent struct for TemplateTemplateContent
type TemplateTemplateContent struct {
	Content interface{} `json:"content"`
	EnvContent interface{} `json:"envContent"`
	EnvVariables interface{} `json:"envVariables"`
	Services interface{} `json:"services"`
	Template TemplateTemplate `json:"template"`
}

type _TemplateTemplateContent TemplateTemplateContent

// NewTemplateTemplateContent instantiates a new TemplateTemplateContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTemplateTemplateContent(content interface{}, envContent interface{}, envVariables interface{}, services interface{}, template TemplateTemplate) *TemplateTemplateContent {
	this := TemplateTemplateContent{}
	this.Content = content
	this.EnvContent = envContent
	this.EnvVariables = envVariables
	this.Services = services
	this.Template = template
	return &this
}

// NewTemplateTemplateContentWithDefaults instantiates a new TemplateTemplateContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTemplateTemplateContentWithDefaults() *TemplateTemplateContent {
	this := TemplateTemplateContent{}
	return &this
}

// GetContent returns the Content field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *TemplateTemplateContent) GetContent() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TemplateTemplateContent) GetContentOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Content) {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *TemplateTemplateContent) SetContent(v interface{}) {
	o.Content = v
}

// GetEnvContent returns the EnvContent field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *TemplateTemplateContent) GetEnvContent() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.EnvContent
}

// GetEnvContentOk returns a tuple with the EnvContent field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TemplateTemplateContent) GetEnvContentOk() (*interface{}, bool) {
	if o == nil || IsNil(o.EnvContent) {
		return nil, false
	}
	return &o.EnvContent, true
}

// SetEnvContent sets field value
func (o *TemplateTemplateContent) SetEnvContent(v interface{}) {
	o.EnvContent = v
}

// GetEnvVariables returns the EnvVariables field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *TemplateTemplateContent) GetEnvVariables() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.EnvVariables
}

// GetEnvVariablesOk returns a tuple with the EnvVariables field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TemplateTemplateContent) GetEnvVariablesOk() (*interface{}, bool) {
	if o == nil || IsNil(o.EnvVariables) {
		return nil, false
	}
	return &o.EnvVariables, true
}

// SetEnvVariables sets field value
func (o *TemplateTemplateContent) SetEnvVariables(v interface{}) {
	o.EnvVariables = v
}

// GetServices returns the Services field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *TemplateTemplateContent) GetServices() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Services
}

// GetServicesOk returns a tuple with the Services field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TemplateTemplateContent) GetServicesOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Services) {
		return nil, false
	}
	return &o.Services, true
}

// SetServices sets field value
func (o *TemplateTemplateContent) SetServices(v interface{}) {
	o.Services = v
}

// GetTemplate returns the Template field value
func (o *TemplateTemplateContent) GetTemplate() TemplateTemplate {
	if o == nil {
		var ret TemplateTemplate
		return ret
	}

	return o.Template
}

// GetTemplateOk returns a tuple with the Template field value
// and a boolean to check if the value has been set.
func (o *TemplateTemplateContent) GetTemplateOk() (*TemplateTemplate, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Template, true
}

// SetTemplate sets field value
func (o *TemplateTemplateContent) SetTemplate(v TemplateTemplate) {
	o.Template = v
}

func (o TemplateTemplateContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TemplateTemplateContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Content != nil {
		toSerialize["content"] = o.Content
	}
	if o.EnvContent != nil {
		toSerialize["envContent"] = o.EnvContent
	}
	if o.EnvVariables != nil {
		toSerialize["envVariables"] = o.EnvVariables
	}
	if o.Services != nil {
		toSerialize["services"] = o.Services
	}
	toSerialize["template"] = o.Template
	return toSerialize, nil
}

func (o *TemplateTemplateContent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"content",
		"envContent",
		"envVariables",
		"services",
		"template",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTemplateTemplateContent := _TemplateTemplateContent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTemplateTemplateContent)

	if err != nil {
		return err
	}

	*o = TemplateTemplateContent(varTemplateTemplateContent)

	return err
}

type NullableTemplateTemplateContent struct {
	value *TemplateTemplateContent
	isSet bool
}

func (v NullableTemplateTemplateContent) Get() *TemplateTemplateContent {
	return v.value
}

func (v *NullableTemplateTemplateContent) Set(val *TemplateTemplateContent) {
	v.value = val
	v.isSet = true
}

func (v NullableTemplateTemplateContent) IsSet() bool {
	return v.isSet
}

func (v *NullableTemplateTemplateContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemplateTemplateContent(val *TemplateTemplateContent) *NullableTemplateTemplateContent {
	return &NullableTemplateTemplateContent{value: val, isSet: true}
}

func (v NullableTemplateTemplateContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemplateTemplateContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


