/*
Arcane API

Modern Docker Management, Designed for Everyone

API version: 1.11.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arcane

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BaseApiResponsePruneReport type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BaseApiResponsePruneReport{}

// BaseApiResponsePruneReport struct for BaseApiResponsePruneReport
type BaseApiResponsePruneReport struct {
	// A URL to the JSON Schema for this object.
	Schema interface{} `json:"$schema,omitempty"`
	// Response data
	Data ImagePruneReport `json:"data"`
	// Whether the request was successful
	Success interface{} `json:"success"`
}

type _BaseApiResponsePruneReport BaseApiResponsePruneReport

// NewBaseApiResponsePruneReport instantiates a new BaseApiResponsePruneReport object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBaseApiResponsePruneReport(data ImagePruneReport, success interface{}) *BaseApiResponsePruneReport {
	this := BaseApiResponsePruneReport{}
	this.Data = data
	this.Success = success
	return &this
}

// NewBaseApiResponsePruneReportWithDefaults instantiates a new BaseApiResponsePruneReport object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBaseApiResponsePruneReportWithDefaults() *BaseApiResponsePruneReport {
	this := BaseApiResponsePruneReport{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BaseApiResponsePruneReport) GetSchema() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BaseApiResponsePruneReport) GetSchemaOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return &o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *BaseApiResponsePruneReport) HasSchema() bool {
	if o != nil && IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given interface{} and assigns it to the Schema field.
func (o *BaseApiResponsePruneReport) SetSchema(v interface{}) {
	o.Schema = v
}

// GetData returns the Data field value
func (o *BaseApiResponsePruneReport) GetData() ImagePruneReport {
	if o == nil {
		var ret ImagePruneReport
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *BaseApiResponsePruneReport) GetDataOk() (*ImagePruneReport, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *BaseApiResponsePruneReport) SetData(v ImagePruneReport) {
	o.Data = v
}

// GetSuccess returns the Success field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *BaseApiResponsePruneReport) GetSuccess() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BaseApiResponsePruneReport) GetSuccessOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *BaseApiResponsePruneReport) SetSuccess(v interface{}) {
	o.Success = v
}

func (o BaseApiResponsePruneReport) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BaseApiResponsePruneReport) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Schema != nil {
		toSerialize["$schema"] = o.Schema
	}
	toSerialize["data"] = o.Data
	if o.Success != nil {
		toSerialize["success"] = o.Success
	}
	return toSerialize, nil
}

func (o *BaseApiResponsePruneReport) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"success",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBaseApiResponsePruneReport := _BaseApiResponsePruneReport{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBaseApiResponsePruneReport)

	if err != nil {
		return err
	}

	*o = BaseApiResponsePruneReport(varBaseApiResponsePruneReport)

	return err
}

type NullableBaseApiResponsePruneReport struct {
	value *BaseApiResponsePruneReport
	isSet bool
}

func (v NullableBaseApiResponsePruneReport) Get() *BaseApiResponsePruneReport {
	return v.value
}

func (v *NullableBaseApiResponsePruneReport) Set(val *BaseApiResponsePruneReport) {
	v.value = val
	v.isSet = true
}

func (v NullableBaseApiResponsePruneReport) IsSet() bool {
	return v.isSet
}

func (v *NullableBaseApiResponsePruneReport) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBaseApiResponsePruneReport(val *BaseApiResponsePruneReport) *NullableBaseApiResponsePruneReport {
	return &NullableBaseApiResponsePruneReport{value: val, isSet: true}
}

func (v NullableBaseApiResponsePruneReport) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBaseApiResponsePruneReport) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


