/*
Arcane API

Modern Docker Management, Designed for Everyone

API version: 1.11.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arcane

import (
	"encoding/json"
)

// checks if the ContainerConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContainerConfig{}

// ContainerConfig struct for ContainerConfig
type ContainerConfig struct {
	Cmd interface{} `json:"cmd,omitempty"`
	Entrypoint interface{} `json:"entrypoint,omitempty"`
	Env interface{} `json:"env,omitempty"`
	User interface{} `json:"user,omitempty"`
	WorkingDir interface{} `json:"workingDir,omitempty"`
}

// NewContainerConfig instantiates a new ContainerConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContainerConfig() *ContainerConfig {
	this := ContainerConfig{}
	return &this
}

// NewContainerConfigWithDefaults instantiates a new ContainerConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContainerConfigWithDefaults() *ContainerConfig {
	this := ContainerConfig{}
	return &this
}

// GetCmd returns the Cmd field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ContainerConfig) GetCmd() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Cmd
}

// GetCmdOk returns a tuple with the Cmd field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ContainerConfig) GetCmdOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Cmd) {
		return nil, false
	}
	return &o.Cmd, true
}

// HasCmd returns a boolean if a field has been set.
func (o *ContainerConfig) HasCmd() bool {
	if o != nil && IsNil(o.Cmd) {
		return true
	}

	return false
}

// SetCmd gets a reference to the given interface{} and assigns it to the Cmd field.
func (o *ContainerConfig) SetCmd(v interface{}) {
	o.Cmd = v
}

// GetEntrypoint returns the Entrypoint field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ContainerConfig) GetEntrypoint() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Entrypoint
}

// GetEntrypointOk returns a tuple with the Entrypoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ContainerConfig) GetEntrypointOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Entrypoint) {
		return nil, false
	}
	return &o.Entrypoint, true
}

// HasEntrypoint returns a boolean if a field has been set.
func (o *ContainerConfig) HasEntrypoint() bool {
	if o != nil && IsNil(o.Entrypoint) {
		return true
	}

	return false
}

// SetEntrypoint gets a reference to the given interface{} and assigns it to the Entrypoint field.
func (o *ContainerConfig) SetEntrypoint(v interface{}) {
	o.Entrypoint = v
}

// GetEnv returns the Env field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ContainerConfig) GetEnv() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Env
}

// GetEnvOk returns a tuple with the Env field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ContainerConfig) GetEnvOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Env) {
		return nil, false
	}
	return &o.Env, true
}

// HasEnv returns a boolean if a field has been set.
func (o *ContainerConfig) HasEnv() bool {
	if o != nil && IsNil(o.Env) {
		return true
	}

	return false
}

// SetEnv gets a reference to the given interface{} and assigns it to the Env field.
func (o *ContainerConfig) SetEnv(v interface{}) {
	o.Env = v
}

// GetUser returns the User field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ContainerConfig) GetUser() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ContainerConfig) GetUserOk() (*interface{}, bool) {
	if o == nil || IsNil(o.User) {
		return nil, false
	}
	return &o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *ContainerConfig) HasUser() bool {
	if o != nil && IsNil(o.User) {
		return true
	}

	return false
}

// SetUser gets a reference to the given interface{} and assigns it to the User field.
func (o *ContainerConfig) SetUser(v interface{}) {
	o.User = v
}

// GetWorkingDir returns the WorkingDir field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ContainerConfig) GetWorkingDir() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.WorkingDir
}

// GetWorkingDirOk returns a tuple with the WorkingDir field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ContainerConfig) GetWorkingDirOk() (*interface{}, bool) {
	if o == nil || IsNil(o.WorkingDir) {
		return nil, false
	}
	return &o.WorkingDir, true
}

// HasWorkingDir returns a boolean if a field has been set.
func (o *ContainerConfig) HasWorkingDir() bool {
	if o != nil && IsNil(o.WorkingDir) {
		return true
	}

	return false
}

// SetWorkingDir gets a reference to the given interface{} and assigns it to the WorkingDir field.
func (o *ContainerConfig) SetWorkingDir(v interface{}) {
	o.WorkingDir = v
}

func (o ContainerConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContainerConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Cmd != nil {
		toSerialize["cmd"] = o.Cmd
	}
	if o.Entrypoint != nil {
		toSerialize["entrypoint"] = o.Entrypoint
	}
	if o.Env != nil {
		toSerialize["env"] = o.Env
	}
	if o.User != nil {
		toSerialize["user"] = o.User
	}
	if o.WorkingDir != nil {
		toSerialize["workingDir"] = o.WorkingDir
	}
	return toSerialize, nil
}

type NullableContainerConfig struct {
	value *ContainerConfig
	isSet bool
}

func (v NullableContainerConfig) Get() *ContainerConfig {
	return v.value
}

func (v *NullableContainerConfig) Set(val *ContainerConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableContainerConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableContainerConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContainerConfig(val *ContainerConfig) *NullableContainerConfig {
	return &NullableContainerConfig{value: val, isSet: true}
}

func (v NullableContainerConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContainerConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


