/*
Arcane API

Modern Docker Management, Designed for Everyone

API version: 1.11.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arcane

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ContainerDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContainerDetails{}

// ContainerDetails struct for ContainerDetails
type ContainerDetails struct {
	Config ContainerConfig `json:"config"`
	Created interface{} `json:"created"`
	HostConfig ContainerHostConfig `json:"hostConfig"`
	Id interface{} `json:"id"`
	Image interface{} `json:"image"`
	ImageId interface{} `json:"imageId"`
	Labels map[string]interface{} `json:"labels,omitempty"`
	Mounts interface{} `json:"mounts"`
	Name interface{} `json:"name"`
	NetworkSettings ContainerNetworkSettings `json:"networkSettings"`
	Ports interface{} `json:"ports"`
	State ContainerState `json:"state"`
}

type _ContainerDetails ContainerDetails

// NewContainerDetails instantiates a new ContainerDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContainerDetails(config ContainerConfig, created interface{}, hostConfig ContainerHostConfig, id interface{}, image interface{}, imageId interface{}, mounts interface{}, name interface{}, networkSettings ContainerNetworkSettings, ports interface{}, state ContainerState) *ContainerDetails {
	this := ContainerDetails{}
	this.Config = config
	this.Created = created
	this.HostConfig = hostConfig
	this.Id = id
	this.Image = image
	this.ImageId = imageId
	this.Mounts = mounts
	this.Name = name
	this.NetworkSettings = networkSettings
	this.Ports = ports
	this.State = state
	return &this
}

// NewContainerDetailsWithDefaults instantiates a new ContainerDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContainerDetailsWithDefaults() *ContainerDetails {
	this := ContainerDetails{}
	return &this
}

// GetConfig returns the Config field value
func (o *ContainerDetails) GetConfig() ContainerConfig {
	if o == nil {
		var ret ContainerConfig
		return ret
	}

	return o.Config
}

// GetConfigOk returns a tuple with the Config field value
// and a boolean to check if the value has been set.
func (o *ContainerDetails) GetConfigOk() (*ContainerConfig, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Config, true
}

// SetConfig sets field value
func (o *ContainerDetails) SetConfig(v ContainerConfig) {
	o.Config = v
}

// GetCreated returns the Created field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *ContainerDetails) GetCreated() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Created
}

// GetCreatedOk returns a tuple with the Created field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ContainerDetails) GetCreatedOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return &o.Created, true
}

// SetCreated sets field value
func (o *ContainerDetails) SetCreated(v interface{}) {
	o.Created = v
}

// GetHostConfig returns the HostConfig field value
func (o *ContainerDetails) GetHostConfig() ContainerHostConfig {
	if o == nil {
		var ret ContainerHostConfig
		return ret
	}

	return o.HostConfig
}

// GetHostConfigOk returns a tuple with the HostConfig field value
// and a boolean to check if the value has been set.
func (o *ContainerDetails) GetHostConfigOk() (*ContainerHostConfig, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HostConfig, true
}

// SetHostConfig sets field value
func (o *ContainerDetails) SetHostConfig(v ContainerHostConfig) {
	o.HostConfig = v
}

// GetId returns the Id field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *ContainerDetails) GetId() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ContainerDetails) GetIdOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ContainerDetails) SetId(v interface{}) {
	o.Id = v
}

// GetImage returns the Image field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *ContainerDetails) GetImage() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Image
}

// GetImageOk returns a tuple with the Image field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ContainerDetails) GetImageOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Image) {
		return nil, false
	}
	return &o.Image, true
}

// SetImage sets field value
func (o *ContainerDetails) SetImage(v interface{}) {
	o.Image = v
}

// GetImageId returns the ImageId field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *ContainerDetails) GetImageId() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.ImageId
}

// GetImageIdOk returns a tuple with the ImageId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ContainerDetails) GetImageIdOk() (*interface{}, bool) {
	if o == nil || IsNil(o.ImageId) {
		return nil, false
	}
	return &o.ImageId, true
}

// SetImageId sets field value
func (o *ContainerDetails) SetImageId(v interface{}) {
	o.ImageId = v
}

// GetLabels returns the Labels field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ContainerDetails) GetLabels() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ContainerDetails) GetLabelsOk() (*map[string]interface{}, bool) {
	if o == nil || IsNil(o.Labels) {
		return nil, false
	}
	return &o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *ContainerDetails) HasLabels() bool {
	if o != nil && IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]interface{} and assigns it to the Labels field.
func (o *ContainerDetails) SetLabels(v map[string]interface{}) {
	o.Labels = v
}

// GetMounts returns the Mounts field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *ContainerDetails) GetMounts() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Mounts
}

// GetMountsOk returns a tuple with the Mounts field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ContainerDetails) GetMountsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Mounts) {
		return nil, false
	}
	return &o.Mounts, true
}

// SetMounts sets field value
func (o *ContainerDetails) SetMounts(v interface{}) {
	o.Mounts = v
}

// GetName returns the Name field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *ContainerDetails) GetName() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ContainerDetails) GetNameOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ContainerDetails) SetName(v interface{}) {
	o.Name = v
}

// GetNetworkSettings returns the NetworkSettings field value
func (o *ContainerDetails) GetNetworkSettings() ContainerNetworkSettings {
	if o == nil {
		var ret ContainerNetworkSettings
		return ret
	}

	return o.NetworkSettings
}

// GetNetworkSettingsOk returns a tuple with the NetworkSettings field value
// and a boolean to check if the value has been set.
func (o *ContainerDetails) GetNetworkSettingsOk() (*ContainerNetworkSettings, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NetworkSettings, true
}

// SetNetworkSettings sets field value
func (o *ContainerDetails) SetNetworkSettings(v ContainerNetworkSettings) {
	o.NetworkSettings = v
}

// GetPorts returns the Ports field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *ContainerDetails) GetPorts() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Ports
}

// GetPortsOk returns a tuple with the Ports field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ContainerDetails) GetPortsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Ports) {
		return nil, false
	}
	return &o.Ports, true
}

// SetPorts sets field value
func (o *ContainerDetails) SetPorts(v interface{}) {
	o.Ports = v
}

// GetState returns the State field value
func (o *ContainerDetails) GetState() ContainerState {
	if o == nil {
		var ret ContainerState
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *ContainerDetails) GetStateOk() (*ContainerState, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *ContainerDetails) SetState(v ContainerState) {
	o.State = v
}

func (o ContainerDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContainerDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["config"] = o.Config
	if o.Created != nil {
		toSerialize["created"] = o.Created
	}
	toSerialize["hostConfig"] = o.HostConfig
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Image != nil {
		toSerialize["image"] = o.Image
	}
	if o.ImageId != nil {
		toSerialize["imageId"] = o.ImageId
	}
	if o.Labels != nil {
		toSerialize["labels"] = o.Labels
	}
	if o.Mounts != nil {
		toSerialize["mounts"] = o.Mounts
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	toSerialize["networkSettings"] = o.NetworkSettings
	if o.Ports != nil {
		toSerialize["ports"] = o.Ports
	}
	toSerialize["state"] = o.State
	return toSerialize, nil
}

func (o *ContainerDetails) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"config",
		"created",
		"hostConfig",
		"id",
		"image",
		"imageId",
		"mounts",
		"name",
		"networkSettings",
		"ports",
		"state",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varContainerDetails := _ContainerDetails{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varContainerDetails)

	if err != nil {
		return err
	}

	*o = ContainerDetails(varContainerDetails)

	return err
}

type NullableContainerDetails struct {
	value *ContainerDetails
	isSet bool
}

func (v NullableContainerDetails) Get() *ContainerDetails {
	return v.value
}

func (v *NullableContainerDetails) Set(val *ContainerDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableContainerDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableContainerDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContainerDetails(val *ContainerDetails) *NullableContainerDetails {
	return &NullableContainerDetails{value: val, isSet: true}
}

func (v NullableContainerDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContainerDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


