/*
Arcane API

Modern Docker Management, Designed for Everyone

API version: 1.11.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arcane

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AuthLogin type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthLogin{}

// AuthLogin struct for AuthLogin
type AuthLogin struct {
	// A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`
	// Password of the user
	Password string `json:"password"`
	// Username of the user
	Username string `json:"username"`
}

type _AuthLogin AuthLogin

// NewAuthLogin instantiates a new AuthLogin object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthLogin(password string, username string) *AuthLogin {
	this := AuthLogin{}
	this.Password = password
	this.Username = username
	return &this
}

// NewAuthLoginWithDefaults instantiates a new AuthLogin object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthLoginWithDefaults() *AuthLogin {
	this := AuthLogin{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *AuthLogin) GetSchema() string {
	if o == nil || IsNil(o.Schema) {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthLogin) GetSchemaOk() (*string, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *AuthLogin) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *AuthLogin) SetSchema(v string) {
	o.Schema = &v
}

// GetPassword returns the Password field value
func (o *AuthLogin) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *AuthLogin) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *AuthLogin) SetPassword(v string) {
	o.Password = v
}

// GetUsername returns the Username field value
func (o *AuthLogin) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *AuthLogin) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *AuthLogin) SetUsername(v string) {
	o.Username = v
}

func (o AuthLogin) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthLogin) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schema) {
		toSerialize["$schema"] = o.Schema
	}
	toSerialize["password"] = o.Password
	toSerialize["username"] = o.Username
	return toSerialize, nil
}

func (o *AuthLogin) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"password",
		"username",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuthLogin := _AuthLogin{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAuthLogin)

	if err != nil {
		return err
	}

	*o = AuthLogin(varAuthLogin)

	return err
}

type NullableAuthLogin struct {
	value *AuthLogin
	isSet bool
}

func (v NullableAuthLogin) Get() *AuthLogin {
	return v.value
}

func (v *NullableAuthLogin) Set(val *AuthLogin) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthLogin) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthLogin) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthLogin(val *AuthLogin) *NullableAuthLogin {
	return &NullableAuthLogin{value: val, isSet: true}
}

func (v NullableAuthLogin) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthLogin) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


