/*
Arcane API

Modern Docker Management, Designed for Everyone

API version: 1.11.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arcane

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AuthOidcStatusInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthOidcStatusInfo{}

// AuthOidcStatusInfo struct for AuthOidcStatusInfo
type AuthOidcStatusInfo struct {
	// A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`
	EnvConfigured bool `json:"envConfigured"`
	EnvForced bool `json:"envForced"`
	MergeAccounts bool `json:"mergeAccounts"`
}

type _AuthOidcStatusInfo AuthOidcStatusInfo

// NewAuthOidcStatusInfo instantiates a new AuthOidcStatusInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthOidcStatusInfo(envConfigured bool, envForced bool, mergeAccounts bool) *AuthOidcStatusInfo {
	this := AuthOidcStatusInfo{}
	this.EnvConfigured = envConfigured
	this.EnvForced = envForced
	this.MergeAccounts = mergeAccounts
	return &this
}

// NewAuthOidcStatusInfoWithDefaults instantiates a new AuthOidcStatusInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthOidcStatusInfoWithDefaults() *AuthOidcStatusInfo {
	this := AuthOidcStatusInfo{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *AuthOidcStatusInfo) GetSchema() string {
	if o == nil || IsNil(o.Schema) {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthOidcStatusInfo) GetSchemaOk() (*string, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *AuthOidcStatusInfo) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *AuthOidcStatusInfo) SetSchema(v string) {
	o.Schema = &v
}

// GetEnvConfigured returns the EnvConfigured field value
func (o *AuthOidcStatusInfo) GetEnvConfigured() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.EnvConfigured
}

// GetEnvConfiguredOk returns a tuple with the EnvConfigured field value
// and a boolean to check if the value has been set.
func (o *AuthOidcStatusInfo) GetEnvConfiguredOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EnvConfigured, true
}

// SetEnvConfigured sets field value
func (o *AuthOidcStatusInfo) SetEnvConfigured(v bool) {
	o.EnvConfigured = v
}

// GetEnvForced returns the EnvForced field value
func (o *AuthOidcStatusInfo) GetEnvForced() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.EnvForced
}

// GetEnvForcedOk returns a tuple with the EnvForced field value
// and a boolean to check if the value has been set.
func (o *AuthOidcStatusInfo) GetEnvForcedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EnvForced, true
}

// SetEnvForced sets field value
func (o *AuthOidcStatusInfo) SetEnvForced(v bool) {
	o.EnvForced = v
}

// GetMergeAccounts returns the MergeAccounts field value
func (o *AuthOidcStatusInfo) GetMergeAccounts() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.MergeAccounts
}

// GetMergeAccountsOk returns a tuple with the MergeAccounts field value
// and a boolean to check if the value has been set.
func (o *AuthOidcStatusInfo) GetMergeAccountsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MergeAccounts, true
}

// SetMergeAccounts sets field value
func (o *AuthOidcStatusInfo) SetMergeAccounts(v bool) {
	o.MergeAccounts = v
}

func (o AuthOidcStatusInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthOidcStatusInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schema) {
		toSerialize["$schema"] = o.Schema
	}
	toSerialize["envConfigured"] = o.EnvConfigured
	toSerialize["envForced"] = o.EnvForced
	toSerialize["mergeAccounts"] = o.MergeAccounts
	return toSerialize, nil
}

func (o *AuthOidcStatusInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"envConfigured",
		"envForced",
		"mergeAccounts",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuthOidcStatusInfo := _AuthOidcStatusInfo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAuthOidcStatusInfo)

	if err != nil {
		return err
	}

	*o = AuthOidcStatusInfo(varAuthOidcStatusInfo)

	return err
}

type NullableAuthOidcStatusInfo struct {
	value *AuthOidcStatusInfo
	isSet bool
}

func (v NullableAuthOidcStatusInfo) Get() *AuthOidcStatusInfo {
	return v.value
}

func (v *NullableAuthOidcStatusInfo) Set(val *AuthOidcStatusInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthOidcStatusInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthOidcStatusInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthOidcStatusInfo(val *AuthOidcStatusInfo) *NullableAuthOidcStatusInfo {
	return &NullableAuthOidcStatusInfo{value: val, isSet: true}
}

func (v NullableAuthOidcStatusInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthOidcStatusInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


