/*
Arcane API

Modern Docker Management, Designed for Everyone

API version: 1.11.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arcane

import (
	"encoding/json"
)

// checks if the DockerSwarmGenericResource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DockerSwarmGenericResource{}

// DockerSwarmGenericResource struct for DockerSwarmGenericResource
type DockerSwarmGenericResource struct {
	DiscreteResourceSpec *DockerSwarmDiscreteGenericResource `json:"DiscreteResourceSpec,omitempty"`
	NamedResourceSpec *DockerSwarmNamedGenericResource `json:"NamedResourceSpec,omitempty"`
}

// NewDockerSwarmGenericResource instantiates a new DockerSwarmGenericResource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDockerSwarmGenericResource() *DockerSwarmGenericResource {
	this := DockerSwarmGenericResource{}
	return &this
}

// NewDockerSwarmGenericResourceWithDefaults instantiates a new DockerSwarmGenericResource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDockerSwarmGenericResourceWithDefaults() *DockerSwarmGenericResource {
	this := DockerSwarmGenericResource{}
	return &this
}

// GetDiscreteResourceSpec returns the DiscreteResourceSpec field value if set, zero value otherwise.
func (o *DockerSwarmGenericResource) GetDiscreteResourceSpec() DockerSwarmDiscreteGenericResource {
	if o == nil || IsNil(o.DiscreteResourceSpec) {
		var ret DockerSwarmDiscreteGenericResource
		return ret
	}
	return *o.DiscreteResourceSpec
}

// GetDiscreteResourceSpecOk returns a tuple with the DiscreteResourceSpec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DockerSwarmGenericResource) GetDiscreteResourceSpecOk() (*DockerSwarmDiscreteGenericResource, bool) {
	if o == nil || IsNil(o.DiscreteResourceSpec) {
		return nil, false
	}
	return o.DiscreteResourceSpec, true
}

// HasDiscreteResourceSpec returns a boolean if a field has been set.
func (o *DockerSwarmGenericResource) HasDiscreteResourceSpec() bool {
	if o != nil && !IsNil(o.DiscreteResourceSpec) {
		return true
	}

	return false
}

// SetDiscreteResourceSpec gets a reference to the given DockerSwarmDiscreteGenericResource and assigns it to the DiscreteResourceSpec field.
func (o *DockerSwarmGenericResource) SetDiscreteResourceSpec(v DockerSwarmDiscreteGenericResource) {
	o.DiscreteResourceSpec = &v
}

// GetNamedResourceSpec returns the NamedResourceSpec field value if set, zero value otherwise.
func (o *DockerSwarmGenericResource) GetNamedResourceSpec() DockerSwarmNamedGenericResource {
	if o == nil || IsNil(o.NamedResourceSpec) {
		var ret DockerSwarmNamedGenericResource
		return ret
	}
	return *o.NamedResourceSpec
}

// GetNamedResourceSpecOk returns a tuple with the NamedResourceSpec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DockerSwarmGenericResource) GetNamedResourceSpecOk() (*DockerSwarmNamedGenericResource, bool) {
	if o == nil || IsNil(o.NamedResourceSpec) {
		return nil, false
	}
	return o.NamedResourceSpec, true
}

// HasNamedResourceSpec returns a boolean if a field has been set.
func (o *DockerSwarmGenericResource) HasNamedResourceSpec() bool {
	if o != nil && !IsNil(o.NamedResourceSpec) {
		return true
	}

	return false
}

// SetNamedResourceSpec gets a reference to the given DockerSwarmNamedGenericResource and assigns it to the NamedResourceSpec field.
func (o *DockerSwarmGenericResource) SetNamedResourceSpec(v DockerSwarmNamedGenericResource) {
	o.NamedResourceSpec = &v
}

func (o DockerSwarmGenericResource) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DockerSwarmGenericResource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DiscreteResourceSpec) {
		toSerialize["DiscreteResourceSpec"] = o.DiscreteResourceSpec
	}
	if !IsNil(o.NamedResourceSpec) {
		toSerialize["NamedResourceSpec"] = o.NamedResourceSpec
	}
	return toSerialize, nil
}

type NullableDockerSwarmGenericResource struct {
	value *DockerSwarmGenericResource
	isSet bool
}

func (v NullableDockerSwarmGenericResource) Get() *DockerSwarmGenericResource {
	return v.value
}

func (v *NullableDockerSwarmGenericResource) Set(val *DockerSwarmGenericResource) {
	v.value = val
	v.isSet = true
}

func (v NullableDockerSwarmGenericResource) IsSet() bool {
	return v.isSet
}

func (v *NullableDockerSwarmGenericResource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDockerSwarmGenericResource(val *DockerSwarmGenericResource) *NullableDockerSwarmGenericResource {
	return &NullableDockerSwarmGenericResource{value: val, isSet: true}
}

func (v NullableDockerSwarmGenericResource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDockerSwarmGenericResource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


