/*
Arcane API

Modern Docker Management, Designed for Everyone

API version: 1.11.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arcane

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ImagePaginatedResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ImagePaginatedResponse{}

// ImagePaginatedResponse struct for ImagePaginatedResponse
type ImagePaginatedResponse struct {
	// A URL to the JSON Schema for this object.
	Schema interface{} `json:"$schema,omitempty"`
	Data interface{} `json:"data"`
	Pagination BasePaginationResponse `json:"pagination"`
	Success interface{} `json:"success"`
}

type _ImagePaginatedResponse ImagePaginatedResponse

// NewImagePaginatedResponse instantiates a new ImagePaginatedResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImagePaginatedResponse(data interface{}, pagination BasePaginationResponse, success interface{}) *ImagePaginatedResponse {
	this := ImagePaginatedResponse{}
	this.Data = data
	this.Pagination = pagination
	this.Success = success
	return &this
}

// NewImagePaginatedResponseWithDefaults instantiates a new ImagePaginatedResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImagePaginatedResponseWithDefaults() *ImagePaginatedResponse {
	this := ImagePaginatedResponse{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ImagePaginatedResponse) GetSchema() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ImagePaginatedResponse) GetSchemaOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return &o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *ImagePaginatedResponse) HasSchema() bool {
	if o != nil && IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given interface{} and assigns it to the Schema field.
func (o *ImagePaginatedResponse) SetSchema(v interface{}) {
	o.Schema = v
}

// GetData returns the Data field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *ImagePaginatedResponse) GetData() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ImagePaginatedResponse) GetDataOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *ImagePaginatedResponse) SetData(v interface{}) {
	o.Data = v
}

// GetPagination returns the Pagination field value
func (o *ImagePaginatedResponse) GetPagination() BasePaginationResponse {
	if o == nil {
		var ret BasePaginationResponse
		return ret
	}

	return o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value
// and a boolean to check if the value has been set.
func (o *ImagePaginatedResponse) GetPaginationOk() (*BasePaginationResponse, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pagination, true
}

// SetPagination sets field value
func (o *ImagePaginatedResponse) SetPagination(v BasePaginationResponse) {
	o.Pagination = v
}

// GetSuccess returns the Success field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *ImagePaginatedResponse) GetSuccess() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ImagePaginatedResponse) GetSuccessOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *ImagePaginatedResponse) SetSuccess(v interface{}) {
	o.Success = v
}

func (o ImagePaginatedResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ImagePaginatedResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Schema != nil {
		toSerialize["$schema"] = o.Schema
	}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	toSerialize["pagination"] = o.Pagination
	if o.Success != nil {
		toSerialize["success"] = o.Success
	}
	return toSerialize, nil
}

func (o *ImagePaginatedResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"pagination",
		"success",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varImagePaginatedResponse := _ImagePaginatedResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varImagePaginatedResponse)

	if err != nil {
		return err
	}

	*o = ImagePaginatedResponse(varImagePaginatedResponse)

	return err
}

type NullableImagePaginatedResponse struct {
	value *ImagePaginatedResponse
	isSet bool
}

func (v NullableImagePaginatedResponse) Get() *ImagePaginatedResponse {
	return v.value
}

func (v *NullableImagePaginatedResponse) Set(val *ImagePaginatedResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableImagePaginatedResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableImagePaginatedResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImagePaginatedResponse(val *ImagePaginatedResponse) *NullableImagePaginatedResponse {
	return &NullableImagePaginatedResponse{value: val, isSet: true}
}

func (v NullableImagePaginatedResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImagePaginatedResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


