/*
Arcane API

Modern Docker Management, Designed for Everyone

API version: 1.11.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arcane

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BaseApiResponseBatchResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BaseApiResponseBatchResponse{}

// BaseApiResponseBatchResponse struct for BaseApiResponseBatchResponse
type BaseApiResponseBatchResponse struct {
	// A URL to the JSON Schema for this object.
	Schema interface{} `json:"$schema,omitempty"`
	// Response data
	Data map[string]ImageupdateResponse `json:"data"`
	// Whether the request was successful
	Success interface{} `json:"success"`
}

type _BaseApiResponseBatchResponse BaseApiResponseBatchResponse

// NewBaseApiResponseBatchResponse instantiates a new BaseApiResponseBatchResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBaseApiResponseBatchResponse(data map[string]ImageupdateResponse, success interface{}) *BaseApiResponseBatchResponse {
	this := BaseApiResponseBatchResponse{}
	this.Data = data
	this.Success = success
	return &this
}

// NewBaseApiResponseBatchResponseWithDefaults instantiates a new BaseApiResponseBatchResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBaseApiResponseBatchResponseWithDefaults() *BaseApiResponseBatchResponse {
	this := BaseApiResponseBatchResponse{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BaseApiResponseBatchResponse) GetSchema() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BaseApiResponseBatchResponse) GetSchemaOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return &o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *BaseApiResponseBatchResponse) HasSchema() bool {
	if o != nil && IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given interface{} and assigns it to the Schema field.
func (o *BaseApiResponseBatchResponse) SetSchema(v interface{}) {
	o.Schema = v
}

// GetData returns the Data field value
// If the value is explicit nil, the zero value for map[string]ImageupdateResponse will be returned
func (o *BaseApiResponseBatchResponse) GetData() map[string]ImageupdateResponse {
	if o == nil {
		var ret map[string]ImageupdateResponse
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BaseApiResponseBatchResponse) GetDataOk() (*map[string]ImageupdateResponse, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *BaseApiResponseBatchResponse) SetData(v map[string]ImageupdateResponse) {
	o.Data = v
}

// GetSuccess returns the Success field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *BaseApiResponseBatchResponse) GetSuccess() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BaseApiResponseBatchResponse) GetSuccessOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *BaseApiResponseBatchResponse) SetSuccess(v interface{}) {
	o.Success = v
}

func (o BaseApiResponseBatchResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BaseApiResponseBatchResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Schema != nil {
		toSerialize["$schema"] = o.Schema
	}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	if o.Success != nil {
		toSerialize["success"] = o.Success
	}
	return toSerialize, nil
}

func (o *BaseApiResponseBatchResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"success",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBaseApiResponseBatchResponse := _BaseApiResponseBatchResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBaseApiResponseBatchResponse)

	if err != nil {
		return err
	}

	*o = BaseApiResponseBatchResponse(varBaseApiResponseBatchResponse)

	return err
}

type NullableBaseApiResponseBatchResponse struct {
	value *BaseApiResponseBatchResponse
	isSet bool
}

func (v NullableBaseApiResponseBatchResponse) Get() *BaseApiResponseBatchResponse {
	return v.value
}

func (v *NullableBaseApiResponseBatchResponse) Set(val *BaseApiResponseBatchResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBaseApiResponseBatchResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBaseApiResponseBatchResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBaseApiResponseBatchResponse(val *BaseApiResponseBatchResponse) *NullableBaseApiResponseBatchResponse {
	return &NullableBaseApiResponseBatchResponse{value: val, isSet: true}
}

func (v NullableBaseApiResponseBatchResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBaseApiResponseBatchResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


