/*
Arcane API

Modern Docker Management, Designed for Everyone

API version: 1.11.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arcane

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SettingsSettingDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SettingsSettingDto{}

// SettingsSettingDto struct for SettingsSettingDto
type SettingsSettingDto struct {
	IsPublic interface{} `json:"isPublic"`
	Key interface{} `json:"key"`
	Type interface{} `json:"type"`
	Value interface{} `json:"value"`
}

type _SettingsSettingDto SettingsSettingDto

// NewSettingsSettingDto instantiates a new SettingsSettingDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSettingsSettingDto(isPublic interface{}, key interface{}, type_ interface{}, value interface{}) *SettingsSettingDto {
	this := SettingsSettingDto{}
	this.IsPublic = isPublic
	this.Key = key
	this.Type = type_
	this.Value = value
	return &this
}

// NewSettingsSettingDtoWithDefaults instantiates a new SettingsSettingDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSettingsSettingDtoWithDefaults() *SettingsSettingDto {
	this := SettingsSettingDto{}
	return &this
}

// GetIsPublic returns the IsPublic field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *SettingsSettingDto) GetIsPublic() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.IsPublic
}

// GetIsPublicOk returns a tuple with the IsPublic field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SettingsSettingDto) GetIsPublicOk() (*interface{}, bool) {
	if o == nil || IsNil(o.IsPublic) {
		return nil, false
	}
	return &o.IsPublic, true
}

// SetIsPublic sets field value
func (o *SettingsSettingDto) SetIsPublic(v interface{}) {
	o.IsPublic = v
}

// GetKey returns the Key field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *SettingsSettingDto) GetKey() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SettingsSettingDto) GetKeyOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *SettingsSettingDto) SetKey(v interface{}) {
	o.Key = v
}

// GetType returns the Type field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *SettingsSettingDto) GetType() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SettingsSettingDto) GetTypeOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *SettingsSettingDto) SetType(v interface{}) {
	o.Type = v
}

// GetValue returns the Value field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *SettingsSettingDto) GetValue() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SettingsSettingDto) GetValueOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *SettingsSettingDto) SetValue(v interface{}) {
	o.Value = v
}

func (o SettingsSettingDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SettingsSettingDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.IsPublic != nil {
		toSerialize["isPublic"] = o.IsPublic
	}
	if o.Key != nil {
		toSerialize["key"] = o.Key
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.Value != nil {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

func (o *SettingsSettingDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"isPublic",
		"key",
		"type",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSettingsSettingDto := _SettingsSettingDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSettingsSettingDto)

	if err != nil {
		return err
	}

	*o = SettingsSettingDto(varSettingsSettingDto)

	return err
}

type NullableSettingsSettingDto struct {
	value *SettingsSettingDto
	isSet bool
}

func (v NullableSettingsSettingDto) Get() *SettingsSettingDto {
	return v.value
}

func (v *NullableSettingsSettingDto) Set(val *SettingsSettingDto) {
	v.value = val
	v.isSet = true
}

func (v NullableSettingsSettingDto) IsSet() bool {
	return v.isSet
}

func (v *NullableSettingsSettingDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSettingsSettingDto(val *SettingsSettingDto) *NullableSettingsSettingDto {
	return &NullableSettingsSettingDto{value: val, isSet: true}
}

func (v NullableSettingsSettingDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSettingsSettingDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


