/*
Arcane API

Modern Docker Management, Designed for Everyone

API version: 1.11.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arcane

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TemplateRemoteTemplate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TemplateRemoteTemplate{}

// TemplateRemoteTemplate struct for TemplateRemoteTemplate
type TemplateRemoteTemplate struct {
	Author interface{} `json:"author"`
	ComposeUrl interface{} `json:"compose_url"`
	Description interface{} `json:"description"`
	DocumentationUrl interface{} `json:"documentation_url"`
	EnvUrl interface{} `json:"env_url"`
	Id interface{} `json:"id"`
	Name interface{} `json:"name"`
	Tags interface{} `json:"tags"`
	Version interface{} `json:"version"`
}

type _TemplateRemoteTemplate TemplateRemoteTemplate

// NewTemplateRemoteTemplate instantiates a new TemplateRemoteTemplate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTemplateRemoteTemplate(author interface{}, composeUrl interface{}, description interface{}, documentationUrl interface{}, envUrl interface{}, id interface{}, name interface{}, tags interface{}, version interface{}) *TemplateRemoteTemplate {
	this := TemplateRemoteTemplate{}
	this.Author = author
	this.ComposeUrl = composeUrl
	this.Description = description
	this.DocumentationUrl = documentationUrl
	this.EnvUrl = envUrl
	this.Id = id
	this.Name = name
	this.Tags = tags
	this.Version = version
	return &this
}

// NewTemplateRemoteTemplateWithDefaults instantiates a new TemplateRemoteTemplate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTemplateRemoteTemplateWithDefaults() *TemplateRemoteTemplate {
	this := TemplateRemoteTemplate{}
	return &this
}

// GetAuthor returns the Author field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *TemplateRemoteTemplate) GetAuthor() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Author
}

// GetAuthorOk returns a tuple with the Author field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TemplateRemoteTemplate) GetAuthorOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Author) {
		return nil, false
	}
	return &o.Author, true
}

// SetAuthor sets field value
func (o *TemplateRemoteTemplate) SetAuthor(v interface{}) {
	o.Author = v
}

// GetComposeUrl returns the ComposeUrl field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *TemplateRemoteTemplate) GetComposeUrl() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.ComposeUrl
}

// GetComposeUrlOk returns a tuple with the ComposeUrl field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TemplateRemoteTemplate) GetComposeUrlOk() (*interface{}, bool) {
	if o == nil || IsNil(o.ComposeUrl) {
		return nil, false
	}
	return &o.ComposeUrl, true
}

// SetComposeUrl sets field value
func (o *TemplateRemoteTemplate) SetComposeUrl(v interface{}) {
	o.ComposeUrl = v
}

// GetDescription returns the Description field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *TemplateRemoteTemplate) GetDescription() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TemplateRemoteTemplate) GetDescriptionOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *TemplateRemoteTemplate) SetDescription(v interface{}) {
	o.Description = v
}

// GetDocumentationUrl returns the DocumentationUrl field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *TemplateRemoteTemplate) GetDocumentationUrl() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.DocumentationUrl
}

// GetDocumentationUrlOk returns a tuple with the DocumentationUrl field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TemplateRemoteTemplate) GetDocumentationUrlOk() (*interface{}, bool) {
	if o == nil || IsNil(o.DocumentationUrl) {
		return nil, false
	}
	return &o.DocumentationUrl, true
}

// SetDocumentationUrl sets field value
func (o *TemplateRemoteTemplate) SetDocumentationUrl(v interface{}) {
	o.DocumentationUrl = v
}

// GetEnvUrl returns the EnvUrl field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *TemplateRemoteTemplate) GetEnvUrl() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.EnvUrl
}

// GetEnvUrlOk returns a tuple with the EnvUrl field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TemplateRemoteTemplate) GetEnvUrlOk() (*interface{}, bool) {
	if o == nil || IsNil(o.EnvUrl) {
		return nil, false
	}
	return &o.EnvUrl, true
}

// SetEnvUrl sets field value
func (o *TemplateRemoteTemplate) SetEnvUrl(v interface{}) {
	o.EnvUrl = v
}

// GetId returns the Id field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *TemplateRemoteTemplate) GetId() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TemplateRemoteTemplate) GetIdOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *TemplateRemoteTemplate) SetId(v interface{}) {
	o.Id = v
}

// GetName returns the Name field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *TemplateRemoteTemplate) GetName() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TemplateRemoteTemplate) GetNameOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *TemplateRemoteTemplate) SetName(v interface{}) {
	o.Name = v
}

// GetTags returns the Tags field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *TemplateRemoteTemplate) GetTags() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TemplateRemoteTemplate) GetTagsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return &o.Tags, true
}

// SetTags sets field value
func (o *TemplateRemoteTemplate) SetTags(v interface{}) {
	o.Tags = v
}

// GetVersion returns the Version field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *TemplateRemoteTemplate) GetVersion() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TemplateRemoteTemplate) GetVersionOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *TemplateRemoteTemplate) SetVersion(v interface{}) {
	o.Version = v
}

func (o TemplateRemoteTemplate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TemplateRemoteTemplate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Author != nil {
		toSerialize["author"] = o.Author
	}
	if o.ComposeUrl != nil {
		toSerialize["compose_url"] = o.ComposeUrl
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.DocumentationUrl != nil {
		toSerialize["documentation_url"] = o.DocumentationUrl
	}
	if o.EnvUrl != nil {
		toSerialize["env_url"] = o.EnvUrl
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Tags != nil {
		toSerialize["tags"] = o.Tags
	}
	if o.Version != nil {
		toSerialize["version"] = o.Version
	}
	return toSerialize, nil
}

func (o *TemplateRemoteTemplate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"author",
		"compose_url",
		"description",
		"documentation_url",
		"env_url",
		"id",
		"name",
		"tags",
		"version",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTemplateRemoteTemplate := _TemplateRemoteTemplate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTemplateRemoteTemplate)

	if err != nil {
		return err
	}

	*o = TemplateRemoteTemplate(varTemplateRemoteTemplate)

	return err
}

type NullableTemplateRemoteTemplate struct {
	value *TemplateRemoteTemplate
	isSet bool
}

func (v NullableTemplateRemoteTemplate) Get() *TemplateRemoteTemplate {
	return v.value
}

func (v *NullableTemplateRemoteTemplate) Set(val *TemplateRemoteTemplate) {
	v.value = val
	v.isSet = true
}

func (v NullableTemplateRemoteTemplate) IsSet() bool {
	return v.isSet
}

func (v *NullableTemplateRemoteTemplate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemplateRemoteTemplate(val *TemplateRemoteTemplate) *NullableTemplateRemoteTemplate {
	return &NullableTemplateRemoteTemplate{value: val, isSet: true}
}

func (v NullableTemplateRemoteTemplate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemplateRemoteTemplate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


