/*
Arcane API

Modern Docker Management, Designed for Everyone

API version: 1.11.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arcane

import (
	"encoding/json"
)

// checks if the UserUpdateUser type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserUpdateUser{}

// UserUpdateUser struct for UserUpdateUser
type UserUpdateUser struct {
	// A URL to the JSON Schema for this object.
	Schema interface{} `json:"$schema,omitempty"`
	// Display name of the user
	DisplayName interface{} `json:"displayName,omitempty"`
	// Email address of the user
	Email interface{} `json:"email,omitempty"`
	// Locale preference of the user
	Locale interface{} `json:"locale,omitempty"`
	// New password for the user
	Password interface{} `json:"password,omitempty"`
	// Roles assigned to the user
	Roles interface{} `json:"roles,omitempty"`
}

// NewUserUpdateUser instantiates a new UserUpdateUser object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserUpdateUser() *UserUpdateUser {
	this := UserUpdateUser{}
	return &this
}

// NewUserUpdateUserWithDefaults instantiates a new UserUpdateUser object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserUpdateUserWithDefaults() *UserUpdateUser {
	this := UserUpdateUser{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserUpdateUser) GetSchema() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserUpdateUser) GetSchemaOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return &o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *UserUpdateUser) HasSchema() bool {
	if o != nil && IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given interface{} and assigns it to the Schema field.
func (o *UserUpdateUser) SetSchema(v interface{}) {
	o.Schema = v
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserUpdateUser) GetDisplayName() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserUpdateUser) GetDisplayNameOk() (*interface{}, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return &o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *UserUpdateUser) HasDisplayName() bool {
	if o != nil && IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given interface{} and assigns it to the DisplayName field.
func (o *UserUpdateUser) SetDisplayName(v interface{}) {
	o.DisplayName = v
}

// GetEmail returns the Email field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserUpdateUser) GetEmail() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserUpdateUser) GetEmailOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return &o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *UserUpdateUser) HasEmail() bool {
	if o != nil && IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given interface{} and assigns it to the Email field.
func (o *UserUpdateUser) SetEmail(v interface{}) {
	o.Email = v
}

// GetLocale returns the Locale field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserUpdateUser) GetLocale() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Locale
}

// GetLocaleOk returns a tuple with the Locale field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserUpdateUser) GetLocaleOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Locale) {
		return nil, false
	}
	return &o.Locale, true
}

// HasLocale returns a boolean if a field has been set.
func (o *UserUpdateUser) HasLocale() bool {
	if o != nil && IsNil(o.Locale) {
		return true
	}

	return false
}

// SetLocale gets a reference to the given interface{} and assigns it to the Locale field.
func (o *UserUpdateUser) SetLocale(v interface{}) {
	o.Locale = v
}

// GetPassword returns the Password field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserUpdateUser) GetPassword() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserUpdateUser) GetPasswordOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return &o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *UserUpdateUser) HasPassword() bool {
	if o != nil && IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given interface{} and assigns it to the Password field.
func (o *UserUpdateUser) SetPassword(v interface{}) {
	o.Password = v
}

// GetRoles returns the Roles field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserUpdateUser) GetRoles() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Roles
}

// GetRolesOk returns a tuple with the Roles field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserUpdateUser) GetRolesOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Roles) {
		return nil, false
	}
	return &o.Roles, true
}

// HasRoles returns a boolean if a field has been set.
func (o *UserUpdateUser) HasRoles() bool {
	if o != nil && IsNil(o.Roles) {
		return true
	}

	return false
}

// SetRoles gets a reference to the given interface{} and assigns it to the Roles field.
func (o *UserUpdateUser) SetRoles(v interface{}) {
	o.Roles = v
}

func (o UserUpdateUser) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserUpdateUser) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Schema != nil {
		toSerialize["$schema"] = o.Schema
	}
	if o.DisplayName != nil {
		toSerialize["displayName"] = o.DisplayName
	}
	if o.Email != nil {
		toSerialize["email"] = o.Email
	}
	if o.Locale != nil {
		toSerialize["locale"] = o.Locale
	}
	if o.Password != nil {
		toSerialize["password"] = o.Password
	}
	if o.Roles != nil {
		toSerialize["roles"] = o.Roles
	}
	return toSerialize, nil
}

type NullableUserUpdateUser struct {
	value *UserUpdateUser
	isSet bool
}

func (v NullableUserUpdateUser) Get() *UserUpdateUser {
	return v.value
}

func (v *NullableUserUpdateUser) Set(val *UserUpdateUser) {
	v.value = val
	v.isSet = true
}

func (v NullableUserUpdateUser) IsSet() bool {
	return v.isSet
}

func (v *NullableUserUpdateUser) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserUpdateUser(val *UserUpdateUser) *NullableUserUpdateUser {
	return &NullableUserUpdateUser{value: val, isSet: true}
}

func (v NullableUserUpdateUser) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserUpdateUser) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


