/*
Arcane API

Modern Docker Management, Designed for Everyone

API version: 1.11.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arcane

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DetailSummaryRootFsStruct type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DetailSummaryRootFsStruct{}

// DetailSummaryRootFsStruct struct for DetailSummaryRootFsStruct
type DetailSummaryRootFsStruct struct {
	Layers interface{} `json:"layers"`
	Type interface{} `json:"type"`
}

type _DetailSummaryRootFsStruct DetailSummaryRootFsStruct

// NewDetailSummaryRootFsStruct instantiates a new DetailSummaryRootFsStruct object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDetailSummaryRootFsStruct(layers interface{}, type_ interface{}) *DetailSummaryRootFsStruct {
	this := DetailSummaryRootFsStruct{}
	this.Layers = layers
	this.Type = type_
	return &this
}

// NewDetailSummaryRootFsStructWithDefaults instantiates a new DetailSummaryRootFsStruct object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDetailSummaryRootFsStructWithDefaults() *DetailSummaryRootFsStruct {
	this := DetailSummaryRootFsStruct{}
	return &this
}

// GetLayers returns the Layers field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *DetailSummaryRootFsStruct) GetLayers() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Layers
}

// GetLayersOk returns a tuple with the Layers field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DetailSummaryRootFsStruct) GetLayersOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Layers) {
		return nil, false
	}
	return &o.Layers, true
}

// SetLayers sets field value
func (o *DetailSummaryRootFsStruct) SetLayers(v interface{}) {
	o.Layers = v
}

// GetType returns the Type field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *DetailSummaryRootFsStruct) GetType() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DetailSummaryRootFsStruct) GetTypeOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *DetailSummaryRootFsStruct) SetType(v interface{}) {
	o.Type = v
}

func (o DetailSummaryRootFsStruct) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DetailSummaryRootFsStruct) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Layers != nil {
		toSerialize["layers"] = o.Layers
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

func (o *DetailSummaryRootFsStruct) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"layers",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDetailSummaryRootFsStruct := _DetailSummaryRootFsStruct{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDetailSummaryRootFsStruct)

	if err != nil {
		return err
	}

	*o = DetailSummaryRootFsStruct(varDetailSummaryRootFsStruct)

	return err
}

type NullableDetailSummaryRootFsStruct struct {
	value *DetailSummaryRootFsStruct
	isSet bool
}

func (v NullableDetailSummaryRootFsStruct) Get() *DetailSummaryRootFsStruct {
	return v.value
}

func (v *NullableDetailSummaryRootFsStruct) Set(val *DetailSummaryRootFsStruct) {
	v.value = val
	v.isSet = true
}

func (v NullableDetailSummaryRootFsStruct) IsSet() bool {
	return v.isSet
}

func (v *NullableDetailSummaryRootFsStruct) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDetailSummaryRootFsStruct(val *DetailSummaryRootFsStruct) *NullableDetailSummaryRootFsStruct {
	return &NullableDetailSummaryRootFsStruct{value: val, isSet: true}
}

func (v NullableDetailSummaryRootFsStruct) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDetailSummaryRootFsStruct) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


