/*
Arcane API

Modern Docker Management, Designed for Everyone

API version: 1.11.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arcane

import (
	"encoding/json"
)

// checks if the DockerTypesDeviceRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DockerTypesDeviceRequest{}

// DockerTypesDeviceRequest struct for DockerTypesDeviceRequest
type DockerTypesDeviceRequest struct {
	Capabilities interface{} `json:"capabilities,omitempty"`
	Count interface{} `json:"count,omitempty"`
	DeviceIds interface{} `json:"device_ids,omitempty"`
	Driver interface{} `json:"driver,omitempty"`
	Options map[string]interface{} `json:"options,omitempty"`
}

// NewDockerTypesDeviceRequest instantiates a new DockerTypesDeviceRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDockerTypesDeviceRequest() *DockerTypesDeviceRequest {
	this := DockerTypesDeviceRequest{}
	return &this
}

// NewDockerTypesDeviceRequestWithDefaults instantiates a new DockerTypesDeviceRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDockerTypesDeviceRequestWithDefaults() *DockerTypesDeviceRequest {
	this := DockerTypesDeviceRequest{}
	return &this
}

// GetCapabilities returns the Capabilities field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DockerTypesDeviceRequest) GetCapabilities() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Capabilities
}

// GetCapabilitiesOk returns a tuple with the Capabilities field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DockerTypesDeviceRequest) GetCapabilitiesOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Capabilities) {
		return nil, false
	}
	return &o.Capabilities, true
}

// HasCapabilities returns a boolean if a field has been set.
func (o *DockerTypesDeviceRequest) HasCapabilities() bool {
	if o != nil && IsNil(o.Capabilities) {
		return true
	}

	return false
}

// SetCapabilities gets a reference to the given interface{} and assigns it to the Capabilities field.
func (o *DockerTypesDeviceRequest) SetCapabilities(v interface{}) {
	o.Capabilities = v
}

// GetCount returns the Count field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DockerTypesDeviceRequest) GetCount() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DockerTypesDeviceRequest) GetCountOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return &o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *DockerTypesDeviceRequest) HasCount() bool {
	if o != nil && IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given interface{} and assigns it to the Count field.
func (o *DockerTypesDeviceRequest) SetCount(v interface{}) {
	o.Count = v
}

// GetDeviceIds returns the DeviceIds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DockerTypesDeviceRequest) GetDeviceIds() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.DeviceIds
}

// GetDeviceIdsOk returns a tuple with the DeviceIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DockerTypesDeviceRequest) GetDeviceIdsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.DeviceIds) {
		return nil, false
	}
	return &o.DeviceIds, true
}

// HasDeviceIds returns a boolean if a field has been set.
func (o *DockerTypesDeviceRequest) HasDeviceIds() bool {
	if o != nil && IsNil(o.DeviceIds) {
		return true
	}

	return false
}

// SetDeviceIds gets a reference to the given interface{} and assigns it to the DeviceIds field.
func (o *DockerTypesDeviceRequest) SetDeviceIds(v interface{}) {
	o.DeviceIds = v
}

// GetDriver returns the Driver field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DockerTypesDeviceRequest) GetDriver() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Driver
}

// GetDriverOk returns a tuple with the Driver field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DockerTypesDeviceRequest) GetDriverOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Driver) {
		return nil, false
	}
	return &o.Driver, true
}

// HasDriver returns a boolean if a field has been set.
func (o *DockerTypesDeviceRequest) HasDriver() bool {
	if o != nil && IsNil(o.Driver) {
		return true
	}

	return false
}

// SetDriver gets a reference to the given interface{} and assigns it to the Driver field.
func (o *DockerTypesDeviceRequest) SetDriver(v interface{}) {
	o.Driver = v
}

// GetOptions returns the Options field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DockerTypesDeviceRequest) GetOptions() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Options
}

// GetOptionsOk returns a tuple with the Options field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DockerTypesDeviceRequest) GetOptionsOk() (*map[string]interface{}, bool) {
	if o == nil || IsNil(o.Options) {
		return nil, false
	}
	return &o.Options, true
}

// HasOptions returns a boolean if a field has been set.
func (o *DockerTypesDeviceRequest) HasOptions() bool {
	if o != nil && IsNil(o.Options) {
		return true
	}

	return false
}

// SetOptions gets a reference to the given map[string]interface{} and assigns it to the Options field.
func (o *DockerTypesDeviceRequest) SetOptions(v map[string]interface{}) {
	o.Options = v
}

func (o DockerTypesDeviceRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DockerTypesDeviceRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Capabilities != nil {
		toSerialize["capabilities"] = o.Capabilities
	}
	if o.Count != nil {
		toSerialize["count"] = o.Count
	}
	if o.DeviceIds != nil {
		toSerialize["device_ids"] = o.DeviceIds
	}
	if o.Driver != nil {
		toSerialize["driver"] = o.Driver
	}
	if o.Options != nil {
		toSerialize["options"] = o.Options
	}
	return toSerialize, nil
}

type NullableDockerTypesDeviceRequest struct {
	value *DockerTypesDeviceRequest
	isSet bool
}

func (v NullableDockerTypesDeviceRequest) Get() *DockerTypesDeviceRequest {
	return v.value
}

func (v *NullableDockerTypesDeviceRequest) Set(val *DockerTypesDeviceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDockerTypesDeviceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDockerTypesDeviceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDockerTypesDeviceRequest(val *DockerTypesDeviceRequest) *NullableDockerTypesDeviceRequest {
	return &NullableDockerTypesDeviceRequest{value: val, isSet: true}
}

func (v NullableDockerTypesDeviceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDockerTypesDeviceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


