/*
Arcane API

Modern Docker Management, Designed for Everyone

API version: 1.11.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arcane

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ImageupdateSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ImageupdateSummary{}

// ImageupdateSummary struct for ImageupdateSummary
type ImageupdateSummary struct {
	DigestUpdates interface{} `json:"digestUpdates"`
	ErrorsCount interface{} `json:"errorsCount"`
	ImagesWithUpdates interface{} `json:"imagesWithUpdates"`
	TotalImages interface{} `json:"totalImages"`
}

type _ImageupdateSummary ImageupdateSummary

// NewImageupdateSummary instantiates a new ImageupdateSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImageupdateSummary(digestUpdates interface{}, errorsCount interface{}, imagesWithUpdates interface{}, totalImages interface{}) *ImageupdateSummary {
	this := ImageupdateSummary{}
	this.DigestUpdates = digestUpdates
	this.ErrorsCount = errorsCount
	this.ImagesWithUpdates = imagesWithUpdates
	this.TotalImages = totalImages
	return &this
}

// NewImageupdateSummaryWithDefaults instantiates a new ImageupdateSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImageupdateSummaryWithDefaults() *ImageupdateSummary {
	this := ImageupdateSummary{}
	return &this
}

// GetDigestUpdates returns the DigestUpdates field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *ImageupdateSummary) GetDigestUpdates() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.DigestUpdates
}

// GetDigestUpdatesOk returns a tuple with the DigestUpdates field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ImageupdateSummary) GetDigestUpdatesOk() (*interface{}, bool) {
	if o == nil || IsNil(o.DigestUpdates) {
		return nil, false
	}
	return &o.DigestUpdates, true
}

// SetDigestUpdates sets field value
func (o *ImageupdateSummary) SetDigestUpdates(v interface{}) {
	o.DigestUpdates = v
}

// GetErrorsCount returns the ErrorsCount field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *ImageupdateSummary) GetErrorsCount() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.ErrorsCount
}

// GetErrorsCountOk returns a tuple with the ErrorsCount field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ImageupdateSummary) GetErrorsCountOk() (*interface{}, bool) {
	if o == nil || IsNil(o.ErrorsCount) {
		return nil, false
	}
	return &o.ErrorsCount, true
}

// SetErrorsCount sets field value
func (o *ImageupdateSummary) SetErrorsCount(v interface{}) {
	o.ErrorsCount = v
}

// GetImagesWithUpdates returns the ImagesWithUpdates field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *ImageupdateSummary) GetImagesWithUpdates() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.ImagesWithUpdates
}

// GetImagesWithUpdatesOk returns a tuple with the ImagesWithUpdates field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ImageupdateSummary) GetImagesWithUpdatesOk() (*interface{}, bool) {
	if o == nil || IsNil(o.ImagesWithUpdates) {
		return nil, false
	}
	return &o.ImagesWithUpdates, true
}

// SetImagesWithUpdates sets field value
func (o *ImageupdateSummary) SetImagesWithUpdates(v interface{}) {
	o.ImagesWithUpdates = v
}

// GetTotalImages returns the TotalImages field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *ImageupdateSummary) GetTotalImages() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.TotalImages
}

// GetTotalImagesOk returns a tuple with the TotalImages field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ImageupdateSummary) GetTotalImagesOk() (*interface{}, bool) {
	if o == nil || IsNil(o.TotalImages) {
		return nil, false
	}
	return &o.TotalImages, true
}

// SetTotalImages sets field value
func (o *ImageupdateSummary) SetTotalImages(v interface{}) {
	o.TotalImages = v
}

func (o ImageupdateSummary) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ImageupdateSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.DigestUpdates != nil {
		toSerialize["digestUpdates"] = o.DigestUpdates
	}
	if o.ErrorsCount != nil {
		toSerialize["errorsCount"] = o.ErrorsCount
	}
	if o.ImagesWithUpdates != nil {
		toSerialize["imagesWithUpdates"] = o.ImagesWithUpdates
	}
	if o.TotalImages != nil {
		toSerialize["totalImages"] = o.TotalImages
	}
	return toSerialize, nil
}

func (o *ImageupdateSummary) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"digestUpdates",
		"errorsCount",
		"imagesWithUpdates",
		"totalImages",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varImageupdateSummary := _ImageupdateSummary{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varImageupdateSummary)

	if err != nil {
		return err
	}

	*o = ImageupdateSummary(varImageupdateSummary)

	return err
}

type NullableImageupdateSummary struct {
	value *ImageupdateSummary
	isSet bool
}

func (v NullableImageupdateSummary) Get() *ImageupdateSummary {
	return v.value
}

func (v *NullableImageupdateSummary) Set(val *ImageupdateSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableImageupdateSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableImageupdateSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImageupdateSummary(val *ImageupdateSummary) *NullableImageupdateSummary {
	return &NullableImageupdateSummary{value: val, isSet: true}
}

func (v NullableImageupdateSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImageupdateSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


