/*
Arcane API

Modern Docker Management, Designed for Everyone

API version: 1.11.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arcane

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VolumeUsageCountsData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VolumeUsageCountsData{}

// VolumeUsageCountsData struct for VolumeUsageCountsData
type VolumeUsageCountsData struct {
	Inuse interface{} `json:"inuse"`
	Total interface{} `json:"total"`
	Unused interface{} `json:"unused"`
}

type _VolumeUsageCountsData VolumeUsageCountsData

// NewVolumeUsageCountsData instantiates a new VolumeUsageCountsData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVolumeUsageCountsData(inuse interface{}, total interface{}, unused interface{}) *VolumeUsageCountsData {
	this := VolumeUsageCountsData{}
	this.Inuse = inuse
	this.Total = total
	this.Unused = unused
	return &this
}

// NewVolumeUsageCountsDataWithDefaults instantiates a new VolumeUsageCountsData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVolumeUsageCountsDataWithDefaults() *VolumeUsageCountsData {
	this := VolumeUsageCountsData{}
	return &this
}

// GetInuse returns the Inuse field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *VolumeUsageCountsData) GetInuse() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Inuse
}

// GetInuseOk returns a tuple with the Inuse field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VolumeUsageCountsData) GetInuseOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Inuse) {
		return nil, false
	}
	return &o.Inuse, true
}

// SetInuse sets field value
func (o *VolumeUsageCountsData) SetInuse(v interface{}) {
	o.Inuse = v
}

// GetTotal returns the Total field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *VolumeUsageCountsData) GetTotal() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VolumeUsageCountsData) GetTotalOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *VolumeUsageCountsData) SetTotal(v interface{}) {
	o.Total = v
}

// GetUnused returns the Unused field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *VolumeUsageCountsData) GetUnused() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Unused
}

// GetUnusedOk returns a tuple with the Unused field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VolumeUsageCountsData) GetUnusedOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Unused) {
		return nil, false
	}
	return &o.Unused, true
}

// SetUnused sets field value
func (o *VolumeUsageCountsData) SetUnused(v interface{}) {
	o.Unused = v
}

func (o VolumeUsageCountsData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VolumeUsageCountsData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Inuse != nil {
		toSerialize["inuse"] = o.Inuse
	}
	if o.Total != nil {
		toSerialize["total"] = o.Total
	}
	if o.Unused != nil {
		toSerialize["unused"] = o.Unused
	}
	return toSerialize, nil
}

func (o *VolumeUsageCountsData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"inuse",
		"total",
		"unused",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVolumeUsageCountsData := _VolumeUsageCountsData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVolumeUsageCountsData)

	if err != nil {
		return err
	}

	*o = VolumeUsageCountsData(varVolumeUsageCountsData)

	return err
}

type NullableVolumeUsageCountsData struct {
	value *VolumeUsageCountsData
	isSet bool
}

func (v NullableVolumeUsageCountsData) Get() *VolumeUsageCountsData {
	return v.value
}

func (v *NullableVolumeUsageCountsData) Set(val *VolumeUsageCountsData) {
	v.value = val
	v.isSet = true
}

func (v NullableVolumeUsageCountsData) IsSet() bool {
	return v.isSet
}

func (v *NullableVolumeUsageCountsData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVolumeUsageCountsData(val *VolumeUsageCountsData) *NullableVolumeUsageCountsData {
	return &NullableVolumeUsageCountsData{value: val, isSet: true}
}

func (v NullableVolumeUsageCountsData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVolumeUsageCountsData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


