/*
Arcane API

Modern Docker Management, Designed for Everyone

API version: 1.11.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arcane

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ContainerregistryContainerRegistry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContainerregistryContainerRegistry{}

// ContainerregistryContainerRegistry struct for ContainerregistryContainerRegistry
type ContainerregistryContainerRegistry struct {
	CreatedAt interface{} `json:"createdAt"`
	Description interface{} `json:"description,omitempty"`
	Enabled interface{} `json:"enabled"`
	Id interface{} `json:"id"`
	Insecure interface{} `json:"insecure"`
	UpdatedAt interface{} `json:"updatedAt"`
	Url interface{} `json:"url"`
	Username interface{} `json:"username"`
}

type _ContainerregistryContainerRegistry ContainerregistryContainerRegistry

// NewContainerregistryContainerRegistry instantiates a new ContainerregistryContainerRegistry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContainerregistryContainerRegistry(createdAt interface{}, enabled interface{}, id interface{}, insecure interface{}, updatedAt interface{}, url interface{}, username interface{}) *ContainerregistryContainerRegistry {
	this := ContainerregistryContainerRegistry{}
	this.CreatedAt = createdAt
	this.Enabled = enabled
	this.Id = id
	this.Insecure = insecure
	this.UpdatedAt = updatedAt
	this.Url = url
	this.Username = username
	return &this
}

// NewContainerregistryContainerRegistryWithDefaults instantiates a new ContainerregistryContainerRegistry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContainerregistryContainerRegistryWithDefaults() *ContainerregistryContainerRegistry {
	this := ContainerregistryContainerRegistry{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *ContainerregistryContainerRegistry) GetCreatedAt() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ContainerregistryContainerRegistry) GetCreatedAtOk() (*interface{}, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *ContainerregistryContainerRegistry) SetCreatedAt(v interface{}) {
	o.CreatedAt = v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ContainerregistryContainerRegistry) GetDescription() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ContainerregistryContainerRegistry) GetDescriptionOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return &o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ContainerregistryContainerRegistry) HasDescription() bool {
	if o != nil && IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given interface{} and assigns it to the Description field.
func (o *ContainerregistryContainerRegistry) SetDescription(v interface{}) {
	o.Description = v
}

// GetEnabled returns the Enabled field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *ContainerregistryContainerRegistry) GetEnabled() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ContainerregistryContainerRegistry) GetEnabledOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *ContainerregistryContainerRegistry) SetEnabled(v interface{}) {
	o.Enabled = v
}

// GetId returns the Id field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *ContainerregistryContainerRegistry) GetId() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ContainerregistryContainerRegistry) GetIdOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ContainerregistryContainerRegistry) SetId(v interface{}) {
	o.Id = v
}

// GetInsecure returns the Insecure field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *ContainerregistryContainerRegistry) GetInsecure() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Insecure
}

// GetInsecureOk returns a tuple with the Insecure field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ContainerregistryContainerRegistry) GetInsecureOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Insecure) {
		return nil, false
	}
	return &o.Insecure, true
}

// SetInsecure sets field value
func (o *ContainerregistryContainerRegistry) SetInsecure(v interface{}) {
	o.Insecure = v
}

// GetUpdatedAt returns the UpdatedAt field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *ContainerregistryContainerRegistry) GetUpdatedAt() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ContainerregistryContainerRegistry) GetUpdatedAtOk() (*interface{}, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *ContainerregistryContainerRegistry) SetUpdatedAt(v interface{}) {
	o.UpdatedAt = v
}

// GetUrl returns the Url field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *ContainerregistryContainerRegistry) GetUrl() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ContainerregistryContainerRegistry) GetUrlOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *ContainerregistryContainerRegistry) SetUrl(v interface{}) {
	o.Url = v
}

// GetUsername returns the Username field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *ContainerregistryContainerRegistry) GetUsername() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ContainerregistryContainerRegistry) GetUsernameOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *ContainerregistryContainerRegistry) SetUsername(v interface{}) {
	o.Username = v
}

func (o ContainerregistryContainerRegistry) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContainerregistryContainerRegistry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.CreatedAt != nil {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.Enabled != nil {
		toSerialize["enabled"] = o.Enabled
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Insecure != nil {
		toSerialize["insecure"] = o.Insecure
	}
	if o.UpdatedAt != nil {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	if o.Url != nil {
		toSerialize["url"] = o.Url
	}
	if o.Username != nil {
		toSerialize["username"] = o.Username
	}
	return toSerialize, nil
}

func (o *ContainerregistryContainerRegistry) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"createdAt",
		"enabled",
		"id",
		"insecure",
		"updatedAt",
		"url",
		"username",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varContainerregistryContainerRegistry := _ContainerregistryContainerRegistry{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varContainerregistryContainerRegistry)

	if err != nil {
		return err
	}

	*o = ContainerregistryContainerRegistry(varContainerregistryContainerRegistry)

	return err
}

type NullableContainerregistryContainerRegistry struct {
	value *ContainerregistryContainerRegistry
	isSet bool
}

func (v NullableContainerregistryContainerRegistry) Get() *ContainerregistryContainerRegistry {
	return v.value
}

func (v *NullableContainerregistryContainerRegistry) Set(val *ContainerregistryContainerRegistry) {
	v.value = val
	v.isSet = true
}

func (v NullableContainerregistryContainerRegistry) IsSet() bool {
	return v.isSet
}

func (v *NullableContainerregistryContainerRegistry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContainerregistryContainerRegistry(val *ContainerregistryContainerRegistry) *NullableContainerregistryContainerRegistry {
	return &NullableContainerregistryContainerRegistry{value: val, isSet: true}
}

func (v NullableContainerregistryContainerRegistry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContainerregistryContainerRegistry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


