/*
Arcane API

Modern Docker Management, Designed for Everyone

API version: 1.11.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arcane

import (
	"encoding/json"
)

// checks if the UpdateConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateConfig{}

// UpdateConfig struct for UpdateConfig
type UpdateConfig struct {
	Delay interface{} `json:"delay,omitempty"`
	FailureAction interface{} `json:"failure_action,omitempty"`
	MaxFailureRatio interface{} `json:"max_failure_ratio,omitempty"`
	Monitor interface{} `json:"monitor,omitempty"`
	Order interface{} `json:"order,omitempty"`
	Parallelism interface{} `json:"parallelism,omitempty"`
}

// NewUpdateConfig instantiates a new UpdateConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateConfig() *UpdateConfig {
	this := UpdateConfig{}
	return &this
}

// NewUpdateConfigWithDefaults instantiates a new UpdateConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateConfigWithDefaults() *UpdateConfig {
	this := UpdateConfig{}
	return &this
}

// GetDelay returns the Delay field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateConfig) GetDelay() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Delay
}

// GetDelayOk returns a tuple with the Delay field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateConfig) GetDelayOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Delay) {
		return nil, false
	}
	return &o.Delay, true
}

// HasDelay returns a boolean if a field has been set.
func (o *UpdateConfig) HasDelay() bool {
	if o != nil && IsNil(o.Delay) {
		return true
	}

	return false
}

// SetDelay gets a reference to the given interface{} and assigns it to the Delay field.
func (o *UpdateConfig) SetDelay(v interface{}) {
	o.Delay = v
}

// GetFailureAction returns the FailureAction field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateConfig) GetFailureAction() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.FailureAction
}

// GetFailureActionOk returns a tuple with the FailureAction field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateConfig) GetFailureActionOk() (*interface{}, bool) {
	if o == nil || IsNil(o.FailureAction) {
		return nil, false
	}
	return &o.FailureAction, true
}

// HasFailureAction returns a boolean if a field has been set.
func (o *UpdateConfig) HasFailureAction() bool {
	if o != nil && IsNil(o.FailureAction) {
		return true
	}

	return false
}

// SetFailureAction gets a reference to the given interface{} and assigns it to the FailureAction field.
func (o *UpdateConfig) SetFailureAction(v interface{}) {
	o.FailureAction = v
}

// GetMaxFailureRatio returns the MaxFailureRatio field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateConfig) GetMaxFailureRatio() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.MaxFailureRatio
}

// GetMaxFailureRatioOk returns a tuple with the MaxFailureRatio field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateConfig) GetMaxFailureRatioOk() (*interface{}, bool) {
	if o == nil || IsNil(o.MaxFailureRatio) {
		return nil, false
	}
	return &o.MaxFailureRatio, true
}

// HasMaxFailureRatio returns a boolean if a field has been set.
func (o *UpdateConfig) HasMaxFailureRatio() bool {
	if o != nil && IsNil(o.MaxFailureRatio) {
		return true
	}

	return false
}

// SetMaxFailureRatio gets a reference to the given interface{} and assigns it to the MaxFailureRatio field.
func (o *UpdateConfig) SetMaxFailureRatio(v interface{}) {
	o.MaxFailureRatio = v
}

// GetMonitor returns the Monitor field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateConfig) GetMonitor() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Monitor
}

// GetMonitorOk returns a tuple with the Monitor field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateConfig) GetMonitorOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Monitor) {
		return nil, false
	}
	return &o.Monitor, true
}

// HasMonitor returns a boolean if a field has been set.
func (o *UpdateConfig) HasMonitor() bool {
	if o != nil && IsNil(o.Monitor) {
		return true
	}

	return false
}

// SetMonitor gets a reference to the given interface{} and assigns it to the Monitor field.
func (o *UpdateConfig) SetMonitor(v interface{}) {
	o.Monitor = v
}

// GetOrder returns the Order field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateConfig) GetOrder() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Order
}

// GetOrderOk returns a tuple with the Order field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateConfig) GetOrderOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Order) {
		return nil, false
	}
	return &o.Order, true
}

// HasOrder returns a boolean if a field has been set.
func (o *UpdateConfig) HasOrder() bool {
	if o != nil && IsNil(o.Order) {
		return true
	}

	return false
}

// SetOrder gets a reference to the given interface{} and assigns it to the Order field.
func (o *UpdateConfig) SetOrder(v interface{}) {
	o.Order = v
}

// GetParallelism returns the Parallelism field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateConfig) GetParallelism() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Parallelism
}

// GetParallelismOk returns a tuple with the Parallelism field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateConfig) GetParallelismOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Parallelism) {
		return nil, false
	}
	return &o.Parallelism, true
}

// HasParallelism returns a boolean if a field has been set.
func (o *UpdateConfig) HasParallelism() bool {
	if o != nil && IsNil(o.Parallelism) {
		return true
	}

	return false
}

// SetParallelism gets a reference to the given interface{} and assigns it to the Parallelism field.
func (o *UpdateConfig) SetParallelism(v interface{}) {
	o.Parallelism = v
}

func (o UpdateConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Delay != nil {
		toSerialize["delay"] = o.Delay
	}
	if o.FailureAction != nil {
		toSerialize["failure_action"] = o.FailureAction
	}
	if o.MaxFailureRatio != nil {
		toSerialize["max_failure_ratio"] = o.MaxFailureRatio
	}
	if o.Monitor != nil {
		toSerialize["monitor"] = o.Monitor
	}
	if o.Order != nil {
		toSerialize["order"] = o.Order
	}
	if o.Parallelism != nil {
		toSerialize["parallelism"] = o.Parallelism
	}
	return toSerialize, nil
}

type NullableUpdateConfig struct {
	value *UpdateConfig
	isSet bool
}

func (v NullableUpdateConfig) Get() *UpdateConfig {
	return v.value
}

func (v *NullableUpdateConfig) Set(val *UpdateConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateConfig(val *UpdateConfig) *NullableUpdateConfig {
	return &NullableUpdateConfig{value: val, isSet: true}
}

func (v NullableUpdateConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


