/*
Arcane API

Modern Docker Management, Designed for Everyone

API version: 1.11.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arcane

import (
	"encoding/json"
)

// checks if the DockerSwarmTaskDefaults type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DockerSwarmTaskDefaults{}

// DockerSwarmTaskDefaults struct for DockerSwarmTaskDefaults
type DockerSwarmTaskDefaults struct {
	LogDriver *DockerSwarmDriver `json:"LogDriver,omitempty"`
}

// NewDockerSwarmTaskDefaults instantiates a new DockerSwarmTaskDefaults object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDockerSwarmTaskDefaults() *DockerSwarmTaskDefaults {
	this := DockerSwarmTaskDefaults{}
	return &this
}

// NewDockerSwarmTaskDefaultsWithDefaults instantiates a new DockerSwarmTaskDefaults object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDockerSwarmTaskDefaultsWithDefaults() *DockerSwarmTaskDefaults {
	this := DockerSwarmTaskDefaults{}
	return &this
}

// GetLogDriver returns the LogDriver field value if set, zero value otherwise.
func (o *DockerSwarmTaskDefaults) GetLogDriver() DockerSwarmDriver {
	if o == nil || IsNil(o.LogDriver) {
		var ret DockerSwarmDriver
		return ret
	}
	return *o.LogDriver
}

// GetLogDriverOk returns a tuple with the LogDriver field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DockerSwarmTaskDefaults) GetLogDriverOk() (*DockerSwarmDriver, bool) {
	if o == nil || IsNil(o.LogDriver) {
		return nil, false
	}
	return o.LogDriver, true
}

// HasLogDriver returns a boolean if a field has been set.
func (o *DockerSwarmTaskDefaults) HasLogDriver() bool {
	if o != nil && !IsNil(o.LogDriver) {
		return true
	}

	return false
}

// SetLogDriver gets a reference to the given DockerSwarmDriver and assigns it to the LogDriver field.
func (o *DockerSwarmTaskDefaults) SetLogDriver(v DockerSwarmDriver) {
	o.LogDriver = &v
}

func (o DockerSwarmTaskDefaults) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DockerSwarmTaskDefaults) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.LogDriver) {
		toSerialize["LogDriver"] = o.LogDriver
	}
	return toSerialize, nil
}

type NullableDockerSwarmTaskDefaults struct {
	value *DockerSwarmTaskDefaults
	isSet bool
}

func (v NullableDockerSwarmTaskDefaults) Get() *DockerSwarmTaskDefaults {
	return v.value
}

func (v *NullableDockerSwarmTaskDefaults) Set(val *DockerSwarmTaskDefaults) {
	v.value = val
	v.isSet = true
}

func (v NullableDockerSwarmTaskDefaults) IsSet() bool {
	return v.isSet
}

func (v *NullableDockerSwarmTaskDefaults) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDockerSwarmTaskDefaults(val *DockerSwarmTaskDefaults) *NullableDockerSwarmTaskDefaults {
	return &NullableDockerSwarmTaskDefaults{value: val, isSet: true}
}

func (v NullableDockerSwarmTaskDefaults) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDockerSwarmTaskDefaults) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


