/*
Arcane API

Modern Docker Management, Designed for Everyone

API version: 1.11.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arcane

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DockerNetworkConfigReference type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DockerNetworkConfigReference{}

// DockerNetworkConfigReference struct for DockerNetworkConfigReference
type DockerNetworkConfigReference struct {
	Network interface{} `json:"Network"`
}

type _DockerNetworkConfigReference DockerNetworkConfigReference

// NewDockerNetworkConfigReference instantiates a new DockerNetworkConfigReference object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDockerNetworkConfigReference(network interface{}) *DockerNetworkConfigReference {
	this := DockerNetworkConfigReference{}
	this.Network = network
	return &this
}

// NewDockerNetworkConfigReferenceWithDefaults instantiates a new DockerNetworkConfigReference object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDockerNetworkConfigReferenceWithDefaults() *DockerNetworkConfigReference {
	this := DockerNetworkConfigReference{}
	return &this
}

// GetNetwork returns the Network field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *DockerNetworkConfigReference) GetNetwork() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Network
}

// GetNetworkOk returns a tuple with the Network field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DockerNetworkConfigReference) GetNetworkOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Network) {
		return nil, false
	}
	return &o.Network, true
}

// SetNetwork sets field value
func (o *DockerNetworkConfigReference) SetNetwork(v interface{}) {
	o.Network = v
}

func (o DockerNetworkConfigReference) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DockerNetworkConfigReference) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Network != nil {
		toSerialize["Network"] = o.Network
	}
	return toSerialize, nil
}

func (o *DockerNetworkConfigReference) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"Network",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDockerNetworkConfigReference := _DockerNetworkConfigReference{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDockerNetworkConfigReference)

	if err != nil {
		return err
	}

	*o = DockerNetworkConfigReference(varDockerNetworkConfigReference)

	return err
}

type NullableDockerNetworkConfigReference struct {
	value *DockerNetworkConfigReference
	isSet bool
}

func (v NullableDockerNetworkConfigReference) Get() *DockerNetworkConfigReference {
	return v.value
}

func (v *NullableDockerNetworkConfigReference) Set(val *DockerNetworkConfigReference) {
	v.value = val
	v.isSet = true
}

func (v NullableDockerNetworkConfigReference) IsSet() bool {
	return v.isSet
}

func (v *NullableDockerNetworkConfigReference) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDockerNetworkConfigReference(val *DockerNetworkConfigReference) *NullableDockerNetworkConfigReference {
	return &NullableDockerNetworkConfigReference{value: val, isSet: true}
}

func (v NullableDockerNetworkConfigReference) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDockerNetworkConfigReference) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


