/*
Arcane API

Modern Docker Management, Designed for Everyone

API version: 1.11.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arcane

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the AuthLoginResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthLoginResponse{}

// AuthLoginResponse struct for AuthLoginResponse
type AuthLoginResponse struct {
	// Expiration time of the access token
	ExpiresAt time.Time `json:"expiresAt"`
	// Refresh token for obtaining new access tokens
	RefreshToken string `json:"refreshToken"`
	// JWT access token
	Token string `json:"token"`
	// Authenticated user information
	User UserUser `json:"user"`
}

type _AuthLoginResponse AuthLoginResponse

// NewAuthLoginResponse instantiates a new AuthLoginResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthLoginResponse(expiresAt time.Time, refreshToken string, token string, user UserUser) *AuthLoginResponse {
	this := AuthLoginResponse{}
	this.ExpiresAt = expiresAt
	this.RefreshToken = refreshToken
	this.Token = token
	this.User = user
	return &this
}

// NewAuthLoginResponseWithDefaults instantiates a new AuthLoginResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthLoginResponseWithDefaults() *AuthLoginResponse {
	this := AuthLoginResponse{}
	return &this
}

// GetExpiresAt returns the ExpiresAt field value
func (o *AuthLoginResponse) GetExpiresAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value
// and a boolean to check if the value has been set.
func (o *AuthLoginResponse) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresAt, true
}

// SetExpiresAt sets field value
func (o *AuthLoginResponse) SetExpiresAt(v time.Time) {
	o.ExpiresAt = v
}

// GetRefreshToken returns the RefreshToken field value
func (o *AuthLoginResponse) GetRefreshToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RefreshToken
}

// GetRefreshTokenOk returns a tuple with the RefreshToken field value
// and a boolean to check if the value has been set.
func (o *AuthLoginResponse) GetRefreshTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RefreshToken, true
}

// SetRefreshToken sets field value
func (o *AuthLoginResponse) SetRefreshToken(v string) {
	o.RefreshToken = v
}

// GetToken returns the Token field value
func (o *AuthLoginResponse) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *AuthLoginResponse) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *AuthLoginResponse) SetToken(v string) {
	o.Token = v
}

// GetUser returns the User field value
func (o *AuthLoginResponse) GetUser() UserUser {
	if o == nil {
		var ret UserUser
		return ret
	}

	return o.User
}

// GetUserOk returns a tuple with the User field value
// and a boolean to check if the value has been set.
func (o *AuthLoginResponse) GetUserOk() (*UserUser, bool) {
	if o == nil {
		return nil, false
	}
	return &o.User, true
}

// SetUser sets field value
func (o *AuthLoginResponse) SetUser(v UserUser) {
	o.User = v
}

func (o AuthLoginResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthLoginResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["expiresAt"] = o.ExpiresAt
	toSerialize["refreshToken"] = o.RefreshToken
	toSerialize["token"] = o.Token
	toSerialize["user"] = o.User
	return toSerialize, nil
}

func (o *AuthLoginResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"expiresAt",
		"refreshToken",
		"token",
		"user",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuthLoginResponse := _AuthLoginResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAuthLoginResponse)

	if err != nil {
		return err
	}

	*o = AuthLoginResponse(varAuthLoginResponse)

	return err
}

type NullableAuthLoginResponse struct {
	value *AuthLoginResponse
	isSet bool
}

func (v NullableAuthLoginResponse) Get() *AuthLoginResponse {
	return v.value
}

func (v *NullableAuthLoginResponse) Set(val *AuthLoginResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthLoginResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthLoginResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthLoginResponse(val *AuthLoginResponse) *NullableAuthLoginResponse {
	return &NullableAuthLoginResponse{value: val, isSet: true}
}

func (v NullableAuthLoginResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthLoginResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


