/*
Arcane API

Modern Docker Management, Designed for Everyone

API version: 1.11.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arcane

import (
	"encoding/json"
)

// checks if the ServiceNetworkConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceNetworkConfig{}

// ServiceNetworkConfig struct for ServiceNetworkConfig
type ServiceNetworkConfig struct {
	Aliases interface{} `json:"aliases,omitempty"`
	DriverOpts map[string]interface{} `json:"driver_opts,omitempty"`
	GwPriority interface{} `json:"gw_priority,omitempty"`
	InterfaceName interface{} `json:"interface_name,omitempty"`
	Ipv4Address interface{} `json:"ipv4_address,omitempty"`
	Ipv6Address interface{} `json:"ipv6_address,omitempty"`
	LinkLocalIps interface{} `json:"link_local_ips,omitempty"`
	MacAddress interface{} `json:"mac_address,omitempty"`
	Priority interface{} `json:"priority,omitempty"`
}

// NewServiceNetworkConfig instantiates a new ServiceNetworkConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceNetworkConfig() *ServiceNetworkConfig {
	this := ServiceNetworkConfig{}
	return &this
}

// NewServiceNetworkConfigWithDefaults instantiates a new ServiceNetworkConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceNetworkConfigWithDefaults() *ServiceNetworkConfig {
	this := ServiceNetworkConfig{}
	return &this
}

// GetAliases returns the Aliases field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ServiceNetworkConfig) GetAliases() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Aliases
}

// GetAliasesOk returns a tuple with the Aliases field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ServiceNetworkConfig) GetAliasesOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Aliases) {
		return nil, false
	}
	return &o.Aliases, true
}

// HasAliases returns a boolean if a field has been set.
func (o *ServiceNetworkConfig) HasAliases() bool {
	if o != nil && IsNil(o.Aliases) {
		return true
	}

	return false
}

// SetAliases gets a reference to the given interface{} and assigns it to the Aliases field.
func (o *ServiceNetworkConfig) SetAliases(v interface{}) {
	o.Aliases = v
}

// GetDriverOpts returns the DriverOpts field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ServiceNetworkConfig) GetDriverOpts() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.DriverOpts
}

// GetDriverOptsOk returns a tuple with the DriverOpts field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ServiceNetworkConfig) GetDriverOptsOk() (*map[string]interface{}, bool) {
	if o == nil || IsNil(o.DriverOpts) {
		return nil, false
	}
	return &o.DriverOpts, true
}

// HasDriverOpts returns a boolean if a field has been set.
func (o *ServiceNetworkConfig) HasDriverOpts() bool {
	if o != nil && IsNil(o.DriverOpts) {
		return true
	}

	return false
}

// SetDriverOpts gets a reference to the given map[string]interface{} and assigns it to the DriverOpts field.
func (o *ServiceNetworkConfig) SetDriverOpts(v map[string]interface{}) {
	o.DriverOpts = v
}

// GetGwPriority returns the GwPriority field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ServiceNetworkConfig) GetGwPriority() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.GwPriority
}

// GetGwPriorityOk returns a tuple with the GwPriority field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ServiceNetworkConfig) GetGwPriorityOk() (*interface{}, bool) {
	if o == nil || IsNil(o.GwPriority) {
		return nil, false
	}
	return &o.GwPriority, true
}

// HasGwPriority returns a boolean if a field has been set.
func (o *ServiceNetworkConfig) HasGwPriority() bool {
	if o != nil && IsNil(o.GwPriority) {
		return true
	}

	return false
}

// SetGwPriority gets a reference to the given interface{} and assigns it to the GwPriority field.
func (o *ServiceNetworkConfig) SetGwPriority(v interface{}) {
	o.GwPriority = v
}

// GetInterfaceName returns the InterfaceName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ServiceNetworkConfig) GetInterfaceName() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.InterfaceName
}

// GetInterfaceNameOk returns a tuple with the InterfaceName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ServiceNetworkConfig) GetInterfaceNameOk() (*interface{}, bool) {
	if o == nil || IsNil(o.InterfaceName) {
		return nil, false
	}
	return &o.InterfaceName, true
}

// HasInterfaceName returns a boolean if a field has been set.
func (o *ServiceNetworkConfig) HasInterfaceName() bool {
	if o != nil && IsNil(o.InterfaceName) {
		return true
	}

	return false
}

// SetInterfaceName gets a reference to the given interface{} and assigns it to the InterfaceName field.
func (o *ServiceNetworkConfig) SetInterfaceName(v interface{}) {
	o.InterfaceName = v
}

// GetIpv4Address returns the Ipv4Address field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ServiceNetworkConfig) GetIpv4Address() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Ipv4Address
}

// GetIpv4AddressOk returns a tuple with the Ipv4Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ServiceNetworkConfig) GetIpv4AddressOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Ipv4Address) {
		return nil, false
	}
	return &o.Ipv4Address, true
}

// HasIpv4Address returns a boolean if a field has been set.
func (o *ServiceNetworkConfig) HasIpv4Address() bool {
	if o != nil && IsNil(o.Ipv4Address) {
		return true
	}

	return false
}

// SetIpv4Address gets a reference to the given interface{} and assigns it to the Ipv4Address field.
func (o *ServiceNetworkConfig) SetIpv4Address(v interface{}) {
	o.Ipv4Address = v
}

// GetIpv6Address returns the Ipv6Address field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ServiceNetworkConfig) GetIpv6Address() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Ipv6Address
}

// GetIpv6AddressOk returns a tuple with the Ipv6Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ServiceNetworkConfig) GetIpv6AddressOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Ipv6Address) {
		return nil, false
	}
	return &o.Ipv6Address, true
}

// HasIpv6Address returns a boolean if a field has been set.
func (o *ServiceNetworkConfig) HasIpv6Address() bool {
	if o != nil && IsNil(o.Ipv6Address) {
		return true
	}

	return false
}

// SetIpv6Address gets a reference to the given interface{} and assigns it to the Ipv6Address field.
func (o *ServiceNetworkConfig) SetIpv6Address(v interface{}) {
	o.Ipv6Address = v
}

// GetLinkLocalIps returns the LinkLocalIps field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ServiceNetworkConfig) GetLinkLocalIps() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.LinkLocalIps
}

// GetLinkLocalIpsOk returns a tuple with the LinkLocalIps field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ServiceNetworkConfig) GetLinkLocalIpsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.LinkLocalIps) {
		return nil, false
	}
	return &o.LinkLocalIps, true
}

// HasLinkLocalIps returns a boolean if a field has been set.
func (o *ServiceNetworkConfig) HasLinkLocalIps() bool {
	if o != nil && IsNil(o.LinkLocalIps) {
		return true
	}

	return false
}

// SetLinkLocalIps gets a reference to the given interface{} and assigns it to the LinkLocalIps field.
func (o *ServiceNetworkConfig) SetLinkLocalIps(v interface{}) {
	o.LinkLocalIps = v
}

// GetMacAddress returns the MacAddress field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ServiceNetworkConfig) GetMacAddress() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.MacAddress
}

// GetMacAddressOk returns a tuple with the MacAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ServiceNetworkConfig) GetMacAddressOk() (*interface{}, bool) {
	if o == nil || IsNil(o.MacAddress) {
		return nil, false
	}
	return &o.MacAddress, true
}

// HasMacAddress returns a boolean if a field has been set.
func (o *ServiceNetworkConfig) HasMacAddress() bool {
	if o != nil && IsNil(o.MacAddress) {
		return true
	}

	return false
}

// SetMacAddress gets a reference to the given interface{} and assigns it to the MacAddress field.
func (o *ServiceNetworkConfig) SetMacAddress(v interface{}) {
	o.MacAddress = v
}

// GetPriority returns the Priority field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ServiceNetworkConfig) GetPriority() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ServiceNetworkConfig) GetPriorityOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Priority) {
		return nil, false
	}
	return &o.Priority, true
}

// HasPriority returns a boolean if a field has been set.
func (o *ServiceNetworkConfig) HasPriority() bool {
	if o != nil && IsNil(o.Priority) {
		return true
	}

	return false
}

// SetPriority gets a reference to the given interface{} and assigns it to the Priority field.
func (o *ServiceNetworkConfig) SetPriority(v interface{}) {
	o.Priority = v
}

func (o ServiceNetworkConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceNetworkConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Aliases != nil {
		toSerialize["aliases"] = o.Aliases
	}
	if o.DriverOpts != nil {
		toSerialize["driver_opts"] = o.DriverOpts
	}
	if o.GwPriority != nil {
		toSerialize["gw_priority"] = o.GwPriority
	}
	if o.InterfaceName != nil {
		toSerialize["interface_name"] = o.InterfaceName
	}
	if o.Ipv4Address != nil {
		toSerialize["ipv4_address"] = o.Ipv4Address
	}
	if o.Ipv6Address != nil {
		toSerialize["ipv6_address"] = o.Ipv6Address
	}
	if o.LinkLocalIps != nil {
		toSerialize["link_local_ips"] = o.LinkLocalIps
	}
	if o.MacAddress != nil {
		toSerialize["mac_address"] = o.MacAddress
	}
	if o.Priority != nil {
		toSerialize["priority"] = o.Priority
	}
	return toSerialize, nil
}

type NullableServiceNetworkConfig struct {
	value *ServiceNetworkConfig
	isSet bool
}

func (v NullableServiceNetworkConfig) Get() *ServiceNetworkConfig {
	return v.value
}

func (v *NullableServiceNetworkConfig) Set(val *ServiceNetworkConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceNetworkConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceNetworkConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceNetworkConfig(val *ServiceNetworkConfig) *NullableServiceNetworkConfig {
	return &NullableServiceNetworkConfig{value: val, isSet: true}
}

func (v NullableServiceNetworkConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceNetworkConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


