/*
Arcane API

Modern Docker Management, Designed for Everyone

API version: 1.11.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arcane

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NetworkCreateResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NetworkCreateResponse{}

// NetworkCreateResponse struct for NetworkCreateResponse
type NetworkCreateResponse struct {
	Id interface{} `json:"id"`
	Warning interface{} `json:"warning,omitempty"`
}

type _NetworkCreateResponse NetworkCreateResponse

// NewNetworkCreateResponse instantiates a new NetworkCreateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNetworkCreateResponse(id interface{}) *NetworkCreateResponse {
	this := NetworkCreateResponse{}
	this.Id = id
	return &this
}

// NewNetworkCreateResponseWithDefaults instantiates a new NetworkCreateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNetworkCreateResponseWithDefaults() *NetworkCreateResponse {
	this := NetworkCreateResponse{}
	return &this
}

// GetId returns the Id field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *NetworkCreateResponse) GetId() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NetworkCreateResponse) GetIdOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *NetworkCreateResponse) SetId(v interface{}) {
	o.Id = v
}

// GetWarning returns the Warning field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NetworkCreateResponse) GetWarning() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Warning
}

// GetWarningOk returns a tuple with the Warning field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NetworkCreateResponse) GetWarningOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Warning) {
		return nil, false
	}
	return &o.Warning, true
}

// HasWarning returns a boolean if a field has been set.
func (o *NetworkCreateResponse) HasWarning() bool {
	if o != nil && IsNil(o.Warning) {
		return true
	}

	return false
}

// SetWarning gets a reference to the given interface{} and assigns it to the Warning field.
func (o *NetworkCreateResponse) SetWarning(v interface{}) {
	o.Warning = v
}

func (o NetworkCreateResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NetworkCreateResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Warning != nil {
		toSerialize["warning"] = o.Warning
	}
	return toSerialize, nil
}

func (o *NetworkCreateResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNetworkCreateResponse := _NetworkCreateResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNetworkCreateResponse)

	if err != nil {
		return err
	}

	*o = NetworkCreateResponse(varNetworkCreateResponse)

	return err
}

type NullableNetworkCreateResponse struct {
	value *NetworkCreateResponse
	isSet bool
}

func (v NullableNetworkCreateResponse) Get() *NetworkCreateResponse {
	return v.value
}

func (v *NullableNetworkCreateResponse) Set(val *NetworkCreateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableNetworkCreateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableNetworkCreateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetworkCreateResponse(val *NetworkCreateResponse) *NullableNetworkCreateResponse {
	return &NullableNetworkCreateResponse{value: val, isSet: true}
}

func (v NullableNetworkCreateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetworkCreateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


