/*
Arcane API

Modern Docker Management, Designed for Everyone

API version: 1.11.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arcane

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DockerTypesTrigger type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DockerTypesTrigger{}

// DockerTypesTrigger struct for DockerTypesTrigger
type DockerTypesTrigger struct {
	Action interface{} `json:"action"`
	Exec *DockerTypesServiceHook `json:"exec,omitempty"`
	Ignore interface{} `json:"ignore,omitempty"`
	Include interface{} `json:"include,omitempty"`
	InitialSync interface{} `json:"initial_sync,omitempty"`
	Path interface{} `json:"path"`
	Target interface{} `json:"target,omitempty"`
}

type _DockerTypesTrigger DockerTypesTrigger

// NewDockerTypesTrigger instantiates a new DockerTypesTrigger object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDockerTypesTrigger(action interface{}, path interface{}) *DockerTypesTrigger {
	this := DockerTypesTrigger{}
	this.Action = action
	this.Path = path
	return &this
}

// NewDockerTypesTriggerWithDefaults instantiates a new DockerTypesTrigger object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDockerTypesTriggerWithDefaults() *DockerTypesTrigger {
	this := DockerTypesTrigger{}
	return &this
}

// GetAction returns the Action field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *DockerTypesTrigger) GetAction() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DockerTypesTrigger) GetActionOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Action) {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *DockerTypesTrigger) SetAction(v interface{}) {
	o.Action = v
}

// GetExec returns the Exec field value if set, zero value otherwise.
func (o *DockerTypesTrigger) GetExec() DockerTypesServiceHook {
	if o == nil || IsNil(o.Exec) {
		var ret DockerTypesServiceHook
		return ret
	}
	return *o.Exec
}

// GetExecOk returns a tuple with the Exec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DockerTypesTrigger) GetExecOk() (*DockerTypesServiceHook, bool) {
	if o == nil || IsNil(o.Exec) {
		return nil, false
	}
	return o.Exec, true
}

// HasExec returns a boolean if a field has been set.
func (o *DockerTypesTrigger) HasExec() bool {
	if o != nil && !IsNil(o.Exec) {
		return true
	}

	return false
}

// SetExec gets a reference to the given DockerTypesServiceHook and assigns it to the Exec field.
func (o *DockerTypesTrigger) SetExec(v DockerTypesServiceHook) {
	o.Exec = &v
}

// GetIgnore returns the Ignore field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DockerTypesTrigger) GetIgnore() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Ignore
}

// GetIgnoreOk returns a tuple with the Ignore field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DockerTypesTrigger) GetIgnoreOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Ignore) {
		return nil, false
	}
	return &o.Ignore, true
}

// HasIgnore returns a boolean if a field has been set.
func (o *DockerTypesTrigger) HasIgnore() bool {
	if o != nil && IsNil(o.Ignore) {
		return true
	}

	return false
}

// SetIgnore gets a reference to the given interface{} and assigns it to the Ignore field.
func (o *DockerTypesTrigger) SetIgnore(v interface{}) {
	o.Ignore = v
}

// GetInclude returns the Include field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DockerTypesTrigger) GetInclude() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Include
}

// GetIncludeOk returns a tuple with the Include field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DockerTypesTrigger) GetIncludeOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Include) {
		return nil, false
	}
	return &o.Include, true
}

// HasInclude returns a boolean if a field has been set.
func (o *DockerTypesTrigger) HasInclude() bool {
	if o != nil && IsNil(o.Include) {
		return true
	}

	return false
}

// SetInclude gets a reference to the given interface{} and assigns it to the Include field.
func (o *DockerTypesTrigger) SetInclude(v interface{}) {
	o.Include = v
}

// GetInitialSync returns the InitialSync field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DockerTypesTrigger) GetInitialSync() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.InitialSync
}

// GetInitialSyncOk returns a tuple with the InitialSync field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DockerTypesTrigger) GetInitialSyncOk() (*interface{}, bool) {
	if o == nil || IsNil(o.InitialSync) {
		return nil, false
	}
	return &o.InitialSync, true
}

// HasInitialSync returns a boolean if a field has been set.
func (o *DockerTypesTrigger) HasInitialSync() bool {
	if o != nil && IsNil(o.InitialSync) {
		return true
	}

	return false
}

// SetInitialSync gets a reference to the given interface{} and assigns it to the InitialSync field.
func (o *DockerTypesTrigger) SetInitialSync(v interface{}) {
	o.InitialSync = v
}

// GetPath returns the Path field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *DockerTypesTrigger) GetPath() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Path
}

// GetPathOk returns a tuple with the Path field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DockerTypesTrigger) GetPathOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Path) {
		return nil, false
	}
	return &o.Path, true
}

// SetPath sets field value
func (o *DockerTypesTrigger) SetPath(v interface{}) {
	o.Path = v
}

// GetTarget returns the Target field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DockerTypesTrigger) GetTarget() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Target
}

// GetTargetOk returns a tuple with the Target field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DockerTypesTrigger) GetTargetOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Target) {
		return nil, false
	}
	return &o.Target, true
}

// HasTarget returns a boolean if a field has been set.
func (o *DockerTypesTrigger) HasTarget() bool {
	if o != nil && IsNil(o.Target) {
		return true
	}

	return false
}

// SetTarget gets a reference to the given interface{} and assigns it to the Target field.
func (o *DockerTypesTrigger) SetTarget(v interface{}) {
	o.Target = v
}

func (o DockerTypesTrigger) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DockerTypesTrigger) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Action != nil {
		toSerialize["action"] = o.Action
	}
	if !IsNil(o.Exec) {
		toSerialize["exec"] = o.Exec
	}
	if o.Ignore != nil {
		toSerialize["ignore"] = o.Ignore
	}
	if o.Include != nil {
		toSerialize["include"] = o.Include
	}
	if o.InitialSync != nil {
		toSerialize["initial_sync"] = o.InitialSync
	}
	if o.Path != nil {
		toSerialize["path"] = o.Path
	}
	if o.Target != nil {
		toSerialize["target"] = o.Target
	}
	return toSerialize, nil
}

func (o *DockerTypesTrigger) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"action",
		"path",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDockerTypesTrigger := _DockerTypesTrigger{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDockerTypesTrigger)

	if err != nil {
		return err
	}

	*o = DockerTypesTrigger(varDockerTypesTrigger)

	return err
}

type NullableDockerTypesTrigger struct {
	value *DockerTypesTrigger
	isSet bool
}

func (v NullableDockerTypesTrigger) Get() *DockerTypesTrigger {
	return v.value
}

func (v *NullableDockerTypesTrigger) Set(val *DockerTypesTrigger) {
	v.value = val
	v.isSet = true
}

func (v NullableDockerTypesTrigger) IsSet() bool {
	return v.isSet
}

func (v *NullableDockerTypesTrigger) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDockerTypesTrigger(val *DockerTypesTrigger) *NullableDockerTypesTrigger {
	return &NullableDockerTypesTrigger{value: val, isSet: true}
}

func (v NullableDockerTypesTrigger) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDockerTypesTrigger) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


