/*
Arcane API

Modern Docker Management, Designed for Everyone

API version: 1.11.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arcane

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BaseApiResponseEnvironmentWithApiKey type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BaseApiResponseEnvironmentWithApiKey{}

// BaseApiResponseEnvironmentWithApiKey struct for BaseApiResponseEnvironmentWithApiKey
type BaseApiResponseEnvironmentWithApiKey struct {
	// A URL to the JSON Schema for this object.
	Schema interface{} `json:"$schema,omitempty"`
	// Response data
	Data EnvironmentWithApiKey `json:"data"`
	// Whether the request was successful
	Success interface{} `json:"success"`
}

type _BaseApiResponseEnvironmentWithApiKey BaseApiResponseEnvironmentWithApiKey

// NewBaseApiResponseEnvironmentWithApiKey instantiates a new BaseApiResponseEnvironmentWithApiKey object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBaseApiResponseEnvironmentWithApiKey(data EnvironmentWithApiKey, success interface{}) *BaseApiResponseEnvironmentWithApiKey {
	this := BaseApiResponseEnvironmentWithApiKey{}
	this.Data = data
	this.Success = success
	return &this
}

// NewBaseApiResponseEnvironmentWithApiKeyWithDefaults instantiates a new BaseApiResponseEnvironmentWithApiKey object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBaseApiResponseEnvironmentWithApiKeyWithDefaults() *BaseApiResponseEnvironmentWithApiKey {
	this := BaseApiResponseEnvironmentWithApiKey{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BaseApiResponseEnvironmentWithApiKey) GetSchema() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BaseApiResponseEnvironmentWithApiKey) GetSchemaOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return &o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *BaseApiResponseEnvironmentWithApiKey) HasSchema() bool {
	if o != nil && IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given interface{} and assigns it to the Schema field.
func (o *BaseApiResponseEnvironmentWithApiKey) SetSchema(v interface{}) {
	o.Schema = v
}

// GetData returns the Data field value
func (o *BaseApiResponseEnvironmentWithApiKey) GetData() EnvironmentWithApiKey {
	if o == nil {
		var ret EnvironmentWithApiKey
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *BaseApiResponseEnvironmentWithApiKey) GetDataOk() (*EnvironmentWithApiKey, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *BaseApiResponseEnvironmentWithApiKey) SetData(v EnvironmentWithApiKey) {
	o.Data = v
}

// GetSuccess returns the Success field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *BaseApiResponseEnvironmentWithApiKey) GetSuccess() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BaseApiResponseEnvironmentWithApiKey) GetSuccessOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *BaseApiResponseEnvironmentWithApiKey) SetSuccess(v interface{}) {
	o.Success = v
}

func (o BaseApiResponseEnvironmentWithApiKey) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BaseApiResponseEnvironmentWithApiKey) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Schema != nil {
		toSerialize["$schema"] = o.Schema
	}
	toSerialize["data"] = o.Data
	if o.Success != nil {
		toSerialize["success"] = o.Success
	}
	return toSerialize, nil
}

func (o *BaseApiResponseEnvironmentWithApiKey) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"success",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBaseApiResponseEnvironmentWithApiKey := _BaseApiResponseEnvironmentWithApiKey{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBaseApiResponseEnvironmentWithApiKey)

	if err != nil {
		return err
	}

	*o = BaseApiResponseEnvironmentWithApiKey(varBaseApiResponseEnvironmentWithApiKey)

	return err
}

type NullableBaseApiResponseEnvironmentWithApiKey struct {
	value *BaseApiResponseEnvironmentWithApiKey
	isSet bool
}

func (v NullableBaseApiResponseEnvironmentWithApiKey) Get() *BaseApiResponseEnvironmentWithApiKey {
	return v.value
}

func (v *NullableBaseApiResponseEnvironmentWithApiKey) Set(val *BaseApiResponseEnvironmentWithApiKey) {
	v.value = val
	v.isSet = true
}

func (v NullableBaseApiResponseEnvironmentWithApiKey) IsSet() bool {
	return v.isSet
}

func (v *NullableBaseApiResponseEnvironmentWithApiKey) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBaseApiResponseEnvironmentWithApiKey(val *BaseApiResponseEnvironmentWithApiKey) *NullableBaseApiResponseEnvironmentWithApiKey {
	return &NullableBaseApiResponseEnvironmentWithApiKey{value: val, isSet: true}
}

func (v NullableBaseApiResponseEnvironmentWithApiKey) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBaseApiResponseEnvironmentWithApiKey) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


