/*
Arcane API

Modern Docker Management, Designed for Everyone

API version: 1.11.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arcane

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VolumeUsageResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VolumeUsageResponse{}

// VolumeUsageResponse struct for VolumeUsageResponse
type VolumeUsageResponse struct {
	Containers interface{} `json:"containers"`
	InUse interface{} `json:"inUse"`
}

type _VolumeUsageResponse VolumeUsageResponse

// NewVolumeUsageResponse instantiates a new VolumeUsageResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVolumeUsageResponse(containers interface{}, inUse interface{}) *VolumeUsageResponse {
	this := VolumeUsageResponse{}
	this.Containers = containers
	this.InUse = inUse
	return &this
}

// NewVolumeUsageResponseWithDefaults instantiates a new VolumeUsageResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVolumeUsageResponseWithDefaults() *VolumeUsageResponse {
	this := VolumeUsageResponse{}
	return &this
}

// GetContainers returns the Containers field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *VolumeUsageResponse) GetContainers() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Containers
}

// GetContainersOk returns a tuple with the Containers field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VolumeUsageResponse) GetContainersOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Containers) {
		return nil, false
	}
	return &o.Containers, true
}

// SetContainers sets field value
func (o *VolumeUsageResponse) SetContainers(v interface{}) {
	o.Containers = v
}

// GetInUse returns the InUse field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *VolumeUsageResponse) GetInUse() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.InUse
}

// GetInUseOk returns a tuple with the InUse field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VolumeUsageResponse) GetInUseOk() (*interface{}, bool) {
	if o == nil || IsNil(o.InUse) {
		return nil, false
	}
	return &o.InUse, true
}

// SetInUse sets field value
func (o *VolumeUsageResponse) SetInUse(v interface{}) {
	o.InUse = v
}

func (o VolumeUsageResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VolumeUsageResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Containers != nil {
		toSerialize["containers"] = o.Containers
	}
	if o.InUse != nil {
		toSerialize["inUse"] = o.InUse
	}
	return toSerialize, nil
}

func (o *VolumeUsageResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"containers",
		"inUse",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVolumeUsageResponse := _VolumeUsageResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVolumeUsageResponse)

	if err != nil {
		return err
	}

	*o = VolumeUsageResponse(varVolumeUsageResponse)

	return err
}

type NullableVolumeUsageResponse struct {
	value *VolumeUsageResponse
	isSet bool
}

func (v NullableVolumeUsageResponse) Get() *VolumeUsageResponse {
	return v.value
}

func (v *NullableVolumeUsageResponse) Set(val *VolumeUsageResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableVolumeUsageResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableVolumeUsageResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVolumeUsageResponse(val *VolumeUsageResponse) *NullableVolumeUsageResponse {
	return &NullableVolumeUsageResponse{value: val, isSet: true}
}

func (v NullableVolumeUsageResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVolumeUsageResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


