/*
Arcane API

Modern Docker Management, Designed for Everyone

API version: 1.11.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arcane

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DockerSwarmClusterInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DockerSwarmClusterInfo{}

// DockerSwarmClusterInfo struct for DockerSwarmClusterInfo
type DockerSwarmClusterInfo struct {
	CreatedAt interface{} `json:"CreatedAt,omitempty"`
	DataPathPort interface{} `json:"DataPathPort"`
	DefaultAddrPool interface{} `json:"DefaultAddrPool"`
	ID interface{} `json:"ID"`
	RootRotationInProgress interface{} `json:"RootRotationInProgress"`
	Spec DockerSwarmSpec `json:"Spec"`
	SubnetSize interface{} `json:"SubnetSize"`
	TLSInfo DockerSwarmTLSInfo `json:"TLSInfo"`
	UpdatedAt interface{} `json:"UpdatedAt,omitempty"`
	Version *DockerSwarmVersion `json:"Version,omitempty"`
}

type _DockerSwarmClusterInfo DockerSwarmClusterInfo

// NewDockerSwarmClusterInfo instantiates a new DockerSwarmClusterInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDockerSwarmClusterInfo(dataPathPort interface{}, defaultAddrPool interface{}, iD interface{}, rootRotationInProgress interface{}, spec DockerSwarmSpec, subnetSize interface{}, tLSInfo DockerSwarmTLSInfo) *DockerSwarmClusterInfo {
	this := DockerSwarmClusterInfo{}
	this.DataPathPort = dataPathPort
	this.DefaultAddrPool = defaultAddrPool
	this.ID = iD
	this.RootRotationInProgress = rootRotationInProgress
	this.Spec = spec
	this.SubnetSize = subnetSize
	this.TLSInfo = tLSInfo
	return &this
}

// NewDockerSwarmClusterInfoWithDefaults instantiates a new DockerSwarmClusterInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDockerSwarmClusterInfoWithDefaults() *DockerSwarmClusterInfo {
	this := DockerSwarmClusterInfo{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DockerSwarmClusterInfo) GetCreatedAt() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DockerSwarmClusterInfo) GetCreatedAtOk() (*interface{}, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return &o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *DockerSwarmClusterInfo) HasCreatedAt() bool {
	if o != nil && IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given interface{} and assigns it to the CreatedAt field.
func (o *DockerSwarmClusterInfo) SetCreatedAt(v interface{}) {
	o.CreatedAt = v
}

// GetDataPathPort returns the DataPathPort field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *DockerSwarmClusterInfo) GetDataPathPort() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.DataPathPort
}

// GetDataPathPortOk returns a tuple with the DataPathPort field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DockerSwarmClusterInfo) GetDataPathPortOk() (*interface{}, bool) {
	if o == nil || IsNil(o.DataPathPort) {
		return nil, false
	}
	return &o.DataPathPort, true
}

// SetDataPathPort sets field value
func (o *DockerSwarmClusterInfo) SetDataPathPort(v interface{}) {
	o.DataPathPort = v
}

// GetDefaultAddrPool returns the DefaultAddrPool field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *DockerSwarmClusterInfo) GetDefaultAddrPool() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.DefaultAddrPool
}

// GetDefaultAddrPoolOk returns a tuple with the DefaultAddrPool field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DockerSwarmClusterInfo) GetDefaultAddrPoolOk() (*interface{}, bool) {
	if o == nil || IsNil(o.DefaultAddrPool) {
		return nil, false
	}
	return &o.DefaultAddrPool, true
}

// SetDefaultAddrPool sets field value
func (o *DockerSwarmClusterInfo) SetDefaultAddrPool(v interface{}) {
	o.DefaultAddrPool = v
}

// GetID returns the ID field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *DockerSwarmClusterInfo) GetID() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.ID
}

// GetIDOk returns a tuple with the ID field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DockerSwarmClusterInfo) GetIDOk() (*interface{}, bool) {
	if o == nil || IsNil(o.ID) {
		return nil, false
	}
	return &o.ID, true
}

// SetID sets field value
func (o *DockerSwarmClusterInfo) SetID(v interface{}) {
	o.ID = v
}

// GetRootRotationInProgress returns the RootRotationInProgress field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *DockerSwarmClusterInfo) GetRootRotationInProgress() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.RootRotationInProgress
}

// GetRootRotationInProgressOk returns a tuple with the RootRotationInProgress field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DockerSwarmClusterInfo) GetRootRotationInProgressOk() (*interface{}, bool) {
	if o == nil || IsNil(o.RootRotationInProgress) {
		return nil, false
	}
	return &o.RootRotationInProgress, true
}

// SetRootRotationInProgress sets field value
func (o *DockerSwarmClusterInfo) SetRootRotationInProgress(v interface{}) {
	o.RootRotationInProgress = v
}

// GetSpec returns the Spec field value
func (o *DockerSwarmClusterInfo) GetSpec() DockerSwarmSpec {
	if o == nil {
		var ret DockerSwarmSpec
		return ret
	}

	return o.Spec
}

// GetSpecOk returns a tuple with the Spec field value
// and a boolean to check if the value has been set.
func (o *DockerSwarmClusterInfo) GetSpecOk() (*DockerSwarmSpec, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Spec, true
}

// SetSpec sets field value
func (o *DockerSwarmClusterInfo) SetSpec(v DockerSwarmSpec) {
	o.Spec = v
}

// GetSubnetSize returns the SubnetSize field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *DockerSwarmClusterInfo) GetSubnetSize() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.SubnetSize
}

// GetSubnetSizeOk returns a tuple with the SubnetSize field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DockerSwarmClusterInfo) GetSubnetSizeOk() (*interface{}, bool) {
	if o == nil || IsNil(o.SubnetSize) {
		return nil, false
	}
	return &o.SubnetSize, true
}

// SetSubnetSize sets field value
func (o *DockerSwarmClusterInfo) SetSubnetSize(v interface{}) {
	o.SubnetSize = v
}

// GetTLSInfo returns the TLSInfo field value
func (o *DockerSwarmClusterInfo) GetTLSInfo() DockerSwarmTLSInfo {
	if o == nil {
		var ret DockerSwarmTLSInfo
		return ret
	}

	return o.TLSInfo
}

// GetTLSInfoOk returns a tuple with the TLSInfo field value
// and a boolean to check if the value has been set.
func (o *DockerSwarmClusterInfo) GetTLSInfoOk() (*DockerSwarmTLSInfo, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TLSInfo, true
}

// SetTLSInfo sets field value
func (o *DockerSwarmClusterInfo) SetTLSInfo(v DockerSwarmTLSInfo) {
	o.TLSInfo = v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DockerSwarmClusterInfo) GetUpdatedAt() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DockerSwarmClusterInfo) GetUpdatedAtOk() (*interface{}, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *DockerSwarmClusterInfo) HasUpdatedAt() bool {
	if o != nil && IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given interface{} and assigns it to the UpdatedAt field.
func (o *DockerSwarmClusterInfo) SetUpdatedAt(v interface{}) {
	o.UpdatedAt = v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *DockerSwarmClusterInfo) GetVersion() DockerSwarmVersion {
	if o == nil || IsNil(o.Version) {
		var ret DockerSwarmVersion
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DockerSwarmClusterInfo) GetVersionOk() (*DockerSwarmVersion, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *DockerSwarmClusterInfo) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given DockerSwarmVersion and assigns it to the Version field.
func (o *DockerSwarmClusterInfo) SetVersion(v DockerSwarmVersion) {
	o.Version = &v
}

func (o DockerSwarmClusterInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DockerSwarmClusterInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.CreatedAt != nil {
		toSerialize["CreatedAt"] = o.CreatedAt
	}
	if o.DataPathPort != nil {
		toSerialize["DataPathPort"] = o.DataPathPort
	}
	if o.DefaultAddrPool != nil {
		toSerialize["DefaultAddrPool"] = o.DefaultAddrPool
	}
	if o.ID != nil {
		toSerialize["ID"] = o.ID
	}
	if o.RootRotationInProgress != nil {
		toSerialize["RootRotationInProgress"] = o.RootRotationInProgress
	}
	toSerialize["Spec"] = o.Spec
	if o.SubnetSize != nil {
		toSerialize["SubnetSize"] = o.SubnetSize
	}
	toSerialize["TLSInfo"] = o.TLSInfo
	if o.UpdatedAt != nil {
		toSerialize["UpdatedAt"] = o.UpdatedAt
	}
	if !IsNil(o.Version) {
		toSerialize["Version"] = o.Version
	}
	return toSerialize, nil
}

func (o *DockerSwarmClusterInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"DataPathPort",
		"DefaultAddrPool",
		"ID",
		"RootRotationInProgress",
		"Spec",
		"SubnetSize",
		"TLSInfo",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDockerSwarmClusterInfo := _DockerSwarmClusterInfo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDockerSwarmClusterInfo)

	if err != nil {
		return err
	}

	*o = DockerSwarmClusterInfo(varDockerSwarmClusterInfo)

	return err
}

type NullableDockerSwarmClusterInfo struct {
	value *DockerSwarmClusterInfo
	isSet bool
}

func (v NullableDockerSwarmClusterInfo) Get() *DockerSwarmClusterInfo {
	return v.value
}

func (v *NullableDockerSwarmClusterInfo) Set(val *DockerSwarmClusterInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableDockerSwarmClusterInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableDockerSwarmClusterInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDockerSwarmClusterInfo(val *DockerSwarmClusterInfo) *NullableDockerSwarmClusterInfo {
	return &NullableDockerSwarmClusterInfo{value: val, isSet: true}
}

func (v NullableDockerSwarmClusterInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDockerSwarmClusterInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


