/*
Arcane API

Modern Docker Management, Designed for Everyone

API version: 1.11.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arcane

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EnvironmentAgentPairResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EnvironmentAgentPairResponse{}

// EnvironmentAgentPairResponse struct for EnvironmentAgentPairResponse
type EnvironmentAgentPairResponse struct {
	Token interface{} `json:"token"`
}

type _EnvironmentAgentPairResponse EnvironmentAgentPairResponse

// NewEnvironmentAgentPairResponse instantiates a new EnvironmentAgentPairResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnvironmentAgentPairResponse(token interface{}) *EnvironmentAgentPairResponse {
	this := EnvironmentAgentPairResponse{}
	this.Token = token
	return &this
}

// NewEnvironmentAgentPairResponseWithDefaults instantiates a new EnvironmentAgentPairResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnvironmentAgentPairResponseWithDefaults() *EnvironmentAgentPairResponse {
	this := EnvironmentAgentPairResponse{}
	return &this
}

// GetToken returns the Token field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *EnvironmentAgentPairResponse) GetToken() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EnvironmentAgentPairResponse) GetTokenOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Token) {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *EnvironmentAgentPairResponse) SetToken(v interface{}) {
	o.Token = v
}

func (o EnvironmentAgentPairResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EnvironmentAgentPairResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Token != nil {
		toSerialize["token"] = o.Token
	}
	return toSerialize, nil
}

func (o *EnvironmentAgentPairResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEnvironmentAgentPairResponse := _EnvironmentAgentPairResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEnvironmentAgentPairResponse)

	if err != nil {
		return err
	}

	*o = EnvironmentAgentPairResponse(varEnvironmentAgentPairResponse)

	return err
}

type NullableEnvironmentAgentPairResponse struct {
	value *EnvironmentAgentPairResponse
	isSet bool
}

func (v NullableEnvironmentAgentPairResponse) Get() *EnvironmentAgentPairResponse {
	return v.value
}

func (v *NullableEnvironmentAgentPairResponse) Set(val *EnvironmentAgentPairResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableEnvironmentAgentPairResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableEnvironmentAgentPairResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnvironmentAgentPairResponse(val *EnvironmentAgentPairResponse) *NullableEnvironmentAgentPairResponse {
	return &NullableEnvironmentAgentPairResponse{value: val, isSet: true}
}

func (v NullableEnvironmentAgentPairResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnvironmentAgentPairResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


